// Code generated by "stringer -type=ConstantName"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmissionCurve-0]
	_ = x[BlocksPerYear-1]
}

const _ConstantName_name = "EmissionCurveBlocksPerYear"

var _ConstantName_index = [...]uint8{0, 13, 26}

func (i ConstantName) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConstantName_index)-1 {
		return "ConstantName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstantName_name[_ConstantName_index[idx]:_ConstantName_index[idx+1]]
}
