version: "2"
run:
  modules-download-mode: readonly
linters:
  settings:
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  exclusions:
    generated: lax
