---
version: 2
project_name: qbtcd
env:
  - CGO_ENABLED=1
builds:
  - id: qbtcd-darwin-arm64
    main: ./cmd/qbtcd
    binary: qbtcd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=qbtc
      - -X github.com/cosmos/cosmos-sdk/version.AppName=qbtcd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm

  - id: qbtcd-linux-amd64
    main: ./cmd/qbtcd
    binary: qbtcd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/libwasmvm_muslc.x86_64.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=qbtc
      - -X github.com/cosmos/cosmos-sdk/version.AppName=qbtcd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -w -s
      - -linkmode=external
      - -extldflags '-L/usr/lib -lwasmvm_muslc.x86_64 -Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
  - id: bifrost-linux-amd64
    main: ./cmd/bifrost
    binary: bifrost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo

  - id: proof-service-linux-amd64
    main: ./cmd/proof-service
    binary: proof-service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo

archives:
  - id: qbtcd-zipped
    builds:
      - qbtcd-linux-amd64
      - qbtcd-darwin-arm64
    name_template: "qbtcd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: qbtcd-binaries
    builds:
      - qbtcd-linux-amd64
      - qbtcd-darwin-arm64
    name_template: "qbtcd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*
  - id: bifrost-zipped
    builds:
      - bifrost-linux-amd64
    name_template: "bifrost-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: bifrost-binaries
    builds:
      - bifrost-linux-amd64
    name_template: "bifrost-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*
  - id: proof-service-zipped
    builds:
      - proof-service-linux-amd64
    name_template: "proof-service-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: proof-service-binaries
    builds:
      - proof-service-linux-amd64
    name_template: "proof-service-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

dockers:
  - id: qbtcd
    ids:
      - qbtcd-linux-amd64
      - bifrost-linux-amd64
    image_templates:
      - "ghcr.io/btcq-org/qbtcd:{{ .Version }}"
      - "ghcr.io/btcq-org/qbtcd:latest"
    dockerfile: docker/Dockerfile.goreleaser.qbtcd
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: proof-service
    ids:
      - proof-service-linux-amd64
    image_templates:
      - "ghcr.io/btcq-org/proof-service:{{ .Version }}"
      - "ghcr.io/btcq-org/proof-service:latest"
    dockerfile: docker/Dockerfile.goreleaser.proofservice
    build_flag_templates:
      - "--platform=linux/amd64"

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

changelog:
  disable: true

release:
  github:
    owner: btcq-org
    name: qbtc
  name_template: "v{{.Version}}"
  mode: replace
  draft: true
  use_existing_draft: true
  replace_existing_artifacts: true