// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Mimir struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Mimir) Reset()         { *m = Mimir{} }
func (m *Mimir) String() string { return proto.CompactTextString(m) }
func (*Mimir) ProtoMessage()    {}
func (*Mimir) Descriptor() ([]byte, []int) {
	return fileDescriptor_8307623358d2b26a, []int{0}
}
func (m *Mimir) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Mimir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Mimir.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Mimir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mimir.Merge(m, src)
}
func (m *Mimir) XXX_Size() int {
	return m.Size()
}
func (m *Mimir) XXX_DiscardUnknown() {
	xxx_messageInfo_Mimir.DiscardUnknown(m)
}

var xxx_messageInfo_Mimir proto.InternalMessageInfo

func (m *Mimir) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Mimir) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// GenesisState defines the btcq module's genesis state.
type GenesisState struct {
	Mimirs        []Mimir              `protobuf:"bytes,1,rep,name=mimirs,proto3" json:"mimirs"`
	PeerAddresses []GenesisPeerAddress `protobuf:"bytes,2,rep,name=peer_addresses,json=peerAddresses,proto3" json:"peer_addresses"`
	Utxos         []*UTXO              `protobuf:"bytes,3,rep,name=utxos,proto3" json:"utxos,omitempty"`
	Params        []*Param             `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	// Airdrop entries mapping Bitcoin address hashes to airdrop amounts
	AirdropEntries []AirdropEntry `protobuf:"bytes,5,rep,name=airdrop_entries,json=airdropEntries,proto3" json:"airdrop_entries"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8307623358d2b26a, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetMimirs() []Mimir {
	if m != nil {
		return m.Mimirs
	}
	return nil
}

func (m *GenesisState) GetPeerAddresses() []GenesisPeerAddress {
	if m != nil {
		return m.PeerAddresses
	}
	return nil
}

func (m *GenesisState) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *GenesisState) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetAirdropEntries() []AirdropEntry {
	if m != nil {
		return m.AirdropEntries
	}
	return nil
}

type GenesisPeerAddress struct {
	Validator   string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	PeerAddress string `protobuf:"bytes,2,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
}

func (m *GenesisPeerAddress) Reset()         { *m = GenesisPeerAddress{} }
func (m *GenesisPeerAddress) String() string { return proto.CompactTextString(m) }
func (*GenesisPeerAddress) ProtoMessage()    {}
func (*GenesisPeerAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8307623358d2b26a, []int{2}
}
func (m *GenesisPeerAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisPeerAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisPeerAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisPeerAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisPeerAddress.Merge(m, src)
}
func (m *GenesisPeerAddress) XXX_Size() int {
	return m.Size()
}
func (m *GenesisPeerAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisPeerAddress.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisPeerAddress proto.InternalMessageInfo

func (m *GenesisPeerAddress) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *GenesisPeerAddress) GetPeerAddress() string {
	if m != nil {
		return m.PeerAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Mimir)(nil), "qbtc.qbtc.v1.mimir")
	proto.RegisterType((*GenesisState)(nil), "qbtc.qbtc.v1.GenesisState")
	proto.RegisterType((*GenesisPeerAddress)(nil), "qbtc.qbtc.v1.GenesisPeerAddress")
}

func init() { proto.RegisterFile("qbtc/qbtc/v1/genesis.proto", fileDescriptor_8307623358d2b26a) }

var fileDescriptor_8307623358d2b26a = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x26, 0x52, 0x36, 0x69, 0x0a, 0x4b, 0x0f, 0x56, 0x54, 0xd9, 0x51, 0x24, 0x44,
	0x10, 0xc2, 0x56, 0xca, 0x07, 0xa0, 0x5a, 0x42, 0x1c, 0xa9, 0x16, 0x90, 0x10, 0x97, 0x68, 0x13,
	0x0f, 0x66, 0x45, 0xed, 0x75, 0x76, 0xd7, 0x56, 0xfd, 0x17, 0x7c, 0x56, 0x8f, 0x3d, 0x72, 0xb2,
	0x90, 0x73, 0xe3, 0x13, 0x38, 0x21, 0xef, 0x1a, 0x61, 0x97, 0x5c, 0xc6, 0xe3, 0x99, 0x37, 0x6f,
	0xf4, 0xde, 0x0e, 0x9a, 0xef, 0xb7, 0x6a, 0xe7, 0xeb, 0x90, 0xaf, 0xfd, 0x08, 0x12, 0x90, 0x4c,
	0x7a, 0xa9, 0xe0, 0x8a, 0xe3, 0x69, 0x5d, 0xf6, 0x74, 0xc8, 0xd7, 0xf3, 0xc7, 0x34, 0x66, 0x09,
	0xf7, 0x75, 0x34, 0x80, 0xf9, 0x79, 0xc4, 0x23, 0xae, 0x53, 0xbf, 0xce, 0x9a, 0xea, 0x45, 0x87,
	0x52, 0x15, 0x29, 0x6c, 0x32, 0x75, 0xfb, 0xb7, 0xeb, 0x76, 0xba, 0xfb, 0x0c, 0x44, 0xb1, 0x49,
	0xa9, 0xa0, 0xb1, 0x3c, 0x0a, 0xd0, 0xe3, 0x94, 0x89, 0x50, 0xf0, 0xd4, 0x00, 0x96, 0x3e, 0x1a,
	0xc6, 0x2c, 0x66, 0x02, 0x3f, 0x42, 0x83, 0x6f, 0x50, 0xd8, 0xd6, 0xc2, 0x5a, 0x8d, 0x49, 0x9d,
	0xe2, 0x73, 0x34, 0xcc, 0xe9, 0x4d, 0x06, 0x76, 0x7f, 0x61, 0xad, 0x06, 0xc4, 0xfc, 0x2c, 0x7f,
	0xf7, 0xd1, 0xf4, 0xad, 0x51, 0xf6, 0x5e, 0x51, 0x05, 0x78, 0x8d, 0x46, 0x9a, 0x41, 0xda, 0xd6,
	0x62, 0xb0, 0x9a, 0x5c, 0x3e, 0xf1, 0xda, 0x4a, 0x3d, 0xdd, 0x0b, 0x4e, 0xee, 0x4a, 0xb7, 0x47,
	0x1a, 0x20, 0x4e, 0xd1, 0x2c, 0x05, 0x10, 0x1b, 0x1a, 0x86, 0x02, 0xa4, 0x04, 0x69, 0xf7, 0xf5,
	0xe8, 0xa2, 0x3b, 0xda, 0xac, 0xb9, 0x06, 0x10, 0x57, 0x06, 0x19, 0x3c, 0xab, 0x79, 0xaa, 0xd2,
	0x3d, 0x6d, 0x15, 0x41, 0xfe, 0x2a, 0xdd, 0x07, 0x84, 0xe4, 0x34, 0x6d, 0x03, 0xf0, 0x0a, 0x0d,
	0x6b, 0xdb, 0xa4, 0x3d, 0xd0, 0x8b, 0x70, 0x77, 0xd1, 0xc7, 0x0f, 0x9f, 0xde, 0x11, 0x03, 0xc0,
	0x2f, 0xd0, 0xc8, 0x38, 0x68, 0x9f, 0x1c, 0x93, 0x73, 0x5d, 0xf7, 0x48, 0x03, 0xc1, 0x09, 0x3a,
	0x6b, 0xec, 0xdc, 0x40, 0xa2, 0x04, 0x03, 0x69, 0x0f, 0xf5, 0xd4, 0xbc, 0x3b, 0x75, 0x65, 0x40,
	0x6f, 0x12, 0x25, 0x8a, 0xe0, 0x79, 0xa3, 0x61, 0xd6, 0xaa, 0x32, 0x2d, 0xe2, 0x21, 0x19, 0x99,
	0xd1, 0x0e, 0x64, 0xf9, 0x05, 0xe1, 0xff, 0x4d, 0xc1, 0x17, 0x68, 0x9c, 0xd3, 0x1b, 0x16, 0x52,
	0xc5, 0x45, 0xf3, 0x80, 0xff, 0x0a, 0xf8, 0x12, 0x4d, 0xdb, 0xde, 0xe8, 0xd7, 0x1c, 0x07, 0x67,
	0x55, 0xe9, 0x4e, 0x5a, 0x24, 0x64, 0xd2, 0x32, 0x2c, 0x78, 0x7d, 0x57, 0x39, 0xd6, 0x7d, 0xe5,
	0x58, 0x3f, 0x2b, 0xc7, 0xfa, 0x7e, 0x70, 0x7a, 0xf7, 0x07, 0xa7, 0xf7, 0xe3, 0xe0, 0xf4, 0x3e,
	0x3f, 0x8d, 0x98, 0xfa, 0x9a, 0x6d, 0xbd, 0x1d, 0x8f, 0xfd, 0xad, 0xda, 0xed, 0x5f, 0x72, 0x11,
	0x99, 0xfb, 0xba, 0x35, 0x9f, 0xfa, 0xc6, 0xe4, 0x76, 0xa4, 0xaf, 0xeb, 0xd5, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x75, 0x69, 0x08, 0x12, 0x03, 0x00, 0x00,
}

func (m *Mimir) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Mimir) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Mimir) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AirdropEntries) > 0 {
		for iNdEx := len(m.AirdropEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AirdropEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Params[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Utxos) > 0 {
		for iNdEx := len(m.Utxos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Utxos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PeerAddresses) > 0 {
		for iNdEx := len(m.PeerAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PeerAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Mimirs) > 0 {
		for iNdEx := len(m.Mimirs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mimirs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisPeerAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisPeerAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisPeerAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PeerAddress) > 0 {
		i -= len(m.PeerAddress)
		copy(dAtA[i:], m.PeerAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PeerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Mimir) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sovGenesis(uint64(m.Value))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Mimirs) > 0 {
		for _, e := range m.Mimirs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PeerAddresses) > 0 {
		for _, e := range m.PeerAddresses {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Utxos) > 0 {
		for _, e := range m.Utxos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Params) > 0 {
		for _, e := range m.Params {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AirdropEntries) > 0 {
		for _, e := range m.AirdropEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisPeerAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.PeerAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Mimir) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: mimir: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: mimir: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mimirs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mimirs = append(m.Mimirs, Mimir{})
			if err := m.Mimirs[len(m.Mimirs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerAddresses = append(m.PeerAddresses, GenesisPeerAddress{})
			if err := m.PeerAddresses[len(m.PeerAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utxos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Utxos = append(m.Utxos, &UTXO{})
			if err := m.Utxos[len(m.Utxos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, &Param{})
			if err := m.Params[len(m.Params)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AirdropEntries = append(m.AirdropEntries, AirdropEntry{})
			if err := m.AirdropEntries[len(m.AirdropEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisPeerAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisPeerAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisPeerAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
