// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/msg_inject_btc_block.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgInjectBtcBlock is injected by the proposing validator during
// PrepareProposal. It carries the agreed minimal block delta together with the
// previous height's ExtendedCommitInfo, which proves that a >2/3 supermajority
// attested the delta digest through their vote extensions. It can only enter a
// block via proposal injection (enforced by the ante handler), never via the
// mempool.
type MsgInjectBtcBlock struct {
	// The minimal Bitcoin block delta to apply to the UTXO set.
	Delta *BtcBlockDelta `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	// Marshaled cometbft abci.ExtendedCommitInfo from height H-1, carrying each
	// validator's vote extension and its precommit signature.
	ExtendedCommitInfo []byte `protobuf:"bytes,2,opt,name=extended_commit_info,json=extendedCommitInfo,proto3" json:"extended_commit_info,omitempty"`
	// Fixed enshrined-bifrost signer address (placeholder; the real authorization
	// is the supermajority proof in extended_commit_info).
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgInjectBtcBlock) Reset()         { *m = MsgInjectBtcBlock{} }
func (m *MsgInjectBtcBlock) String() string { return proto.CompactTextString(m) }
func (*MsgInjectBtcBlock) ProtoMessage()    {}
func (*MsgInjectBtcBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef3e89fb79b4f102, []int{0}
}
func (m *MsgInjectBtcBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInjectBtcBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInjectBtcBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInjectBtcBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInjectBtcBlock.Merge(m, src)
}
func (m *MsgInjectBtcBlock) XXX_Size() int {
	return m.Size()
}
func (m *MsgInjectBtcBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInjectBtcBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInjectBtcBlock proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInjectBtcBlock)(nil), "qbtc.qbtc.v1.MsgInjectBtcBlock")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/msg_inject_btc_block.proto", fileDescriptor_ef3e89fb79b4f102)
}

var fileDescriptor_ef3e89fb79b4f102 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0xfa, 0x40,
	0x1c, 0xc6, 0x7b, 0xbf, 0x5f, 0x24, 0xb1, 0xb2, 0xd0, 0x10, 0xad, 0x98, 0x5c, 0x88, 0x89, 0x4a,
	0x48, 0x68, 0x41, 0x37, 0x37, 0xab, 0x0b, 0x31, 0x2e, 0xb8, 0xb9, 0x34, 0xf4, 0x7a, 0x9c, 0x55,
	0x7a, 0x07, 0xbd, 0x93, 0xe0, 0x66, 0x1c, 0x9d, 0x7c, 0x29, 0x0c, 0xbe, 0x08, 0x46, 0xc2, 0xc4,
	0x28, 0x65, 0xe0, 0x6d, 0x98, 0xfb, 0x43, 0xd4, 0xb8, 0x7c, 0xdb, 0xef, 0xf7, 0xf9, 0xe4, 0xc9,
	0x73, 0x8f, 0x7d, 0x32, 0x8c, 0x04, 0xf2, 0xd5, 0x18, 0xb5, 0xfc, 0x94, 0x93, 0x30, 0xa1, 0x0f,
	0x18, 0x89, 0x30, 0x12, 0x28, 0x8c, 0xfa, 0x0c, 0x3d, 0x7a, 0x83, 0x8c, 0x09, 0xe6, 0x14, 0x25,
	0xe3, 0xa9, 0x31, 0x6a, 0x55, 0x4a, 0xdd, 0x34, 0xa1, 0xcc, 0x57, 0x53, 0x03, 0x95, 0x3d, 0xc4,
	0x78, 0xca, 0xb8, 0xf4, 0x30, 0x56, 0x46, 0xd8, 0xd7, 0x42, 0xa8, 0x36, 0x5f, 0x2f, 0x46, 0x2a,
	0x13, 0x46, 0x98, 0xbe, 0xcb, 0x3f, 0x73, 0xfd, 0x9d, 0x49, 0x3c, 0x0f, 0xf0, 0x77, 0x9a, 0x30,
	0xc6, 0x7d, 0xd1, 0xd5, 0xe0, 0xe1, 0x1c, 0xd8, 0xa5, 0x1b, 0x4e, 0xda, 0x2a, 0x71, 0x20, 0x50,
	0x20, 0x09, 0xa7, 0x65, 0x6f, 0x29, 0xc8, 0x05, 0x55, 0x50, 0xdb, 0x39, 0x3d, 0xf0, 0x7e, 0x26,
	0xf7, 0x36, 0xd8, 0x95, 0x44, 0x3a, 0x9a, 0x74, 0x9a, 0x76, 0x19, 0x8f, 0x05, 0xa6, 0x31, 0x8e,
	0x43, 0xc4, 0xd2, 0x34, 0x11, 0x61, 0x42, 0x7b, 0xcc, 0xfd, 0x57, 0x05, 0xb5, 0x62, 0xc7, 0xd9,
	0x68, 0x97, 0x4a, 0x6a, 0xd3, 0x1e, 0x73, 0x9a, 0x76, 0x81, 0x27, 0x84, 0xe2, 0xcc, 0xfd, 0x5f,
	0x05, 0xb5, 0xed, 0xc0, 0x9d, 0x7f, 0x34, 0xca, 0xe6, 0x6d, 0x17, 0x71, 0x9c, 0x61, 0xce, 0x6f,
	0x45, 0x96, 0x50, 0xd2, 0x31, 0xdc, 0xf9, 0xf1, 0xeb, 0x7a, 0x52, 0x37, 0xcb, 0xdb, 0x7a, 0x52,
	0xdf, 0x8d, 0x04, 0x1a, 0xfa, 0x7f, 0xe2, 0x07, 0xd7, 0xd3, 0x25, 0xb4, 0x16, 0x4b, 0x08, 0x5e,
	0x72, 0x68, 0x4d, 0x73, 0x08, 0x66, 0x39, 0x04, 0x9f, 0x39, 0x04, 0xef, 0x2b, 0x68, 0xcd, 0x56,
	0xd0, 0x5a, 0xac, 0xa0, 0x75, 0x77, 0x44, 0x12, 0x71, 0xff, 0x14, 0x79, 0x88, 0xa5, 0xbe, 0x34,
	0x6a, 0xb0, 0x8c, 0xe8, 0xca, 0xc6, 0xfa, 0x23, 0x6b, 0xe3, 0x51, 0x41, 0x15, 0x75, 0xf6, 0x15,
	0x00, 0x00, 0xff, 0xff, 0xfe, 0x82, 0x63, 0xed, 0xe7, 0x01, 0x00, 0x00,
}

func (m *MsgInjectBtcBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInjectBtcBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInjectBtcBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgInjectBtcBlock(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ExtendedCommitInfo) > 0 {
		i -= len(m.ExtendedCommitInfo)
		copy(dAtA[i:], m.ExtendedCommitInfo)
		i = encodeVarintMsgInjectBtcBlock(dAtA, i, uint64(len(m.ExtendedCommitInfo)))
		i--
		dAtA[i] = 0x12
	}
	if m.Delta != nil {
		{
			size, err := m.Delta.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgInjectBtcBlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgInjectBtcBlock(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgInjectBtcBlock(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInjectBtcBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Delta != nil {
		l = m.Delta.Size()
		n += 1 + l + sovMsgInjectBtcBlock(uint64(l))
	}
	l = len(m.ExtendedCommitInfo)
	if l > 0 {
		n += 1 + l + sovMsgInjectBtcBlock(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgInjectBtcBlock(uint64(l))
	}
	return n
}

func sovMsgInjectBtcBlock(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgInjectBtcBlock(x uint64) (n int) {
	return sovMsgInjectBtcBlock(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInjectBtcBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgInjectBtcBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInjectBtcBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInjectBtcBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgInjectBtcBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Delta == nil {
				m.Delta = &BtcBlockDelta{}
			}
			if err := m.Delta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedCommitInfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgInjectBtcBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtendedCommitInfo = append(m.ExtendedCommitInfo[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtendedCommitInfo == nil {
				m.ExtendedCommitInfo = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgInjectBtcBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgInjectBtcBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgInjectBtcBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgInjectBtcBlock(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgInjectBtcBlock
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgInjectBtcBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgInjectBtcBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgInjectBtcBlock
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgInjectBtcBlock
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgInjectBtcBlock
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgInjectBtcBlock        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgInjectBtcBlock          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgInjectBtcBlock = fmt.Errorf("proto: unexpected end of group")
)
