// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/msg_claim_airdrop.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgClaimAirdrop is the message for claiming an airdrop using a ZK proof.
// The user proves ownership of a Bitcoin address without revealing their private key.
type MsgClaimAirdrop struct {
	// The address on the qbtc chain that will receive the airdrop
	Claimer string `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	// The Hash160 of the Bitcoin public key being claimed (20 bytes)
	BtcAddressHash []byte `protobuf:"bytes,2,opt,name=btc_address_hash,json=btcAddressHash,proto3" json:"btc_address_hash,omitempty"`
	// The ZK proof proving ownership of the Bitcoin address
	Proof ZKProof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof"`
}

func (m *MsgClaimAirdrop) Reset()         { *m = MsgClaimAirdrop{} }
func (m *MsgClaimAirdrop) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAirdrop) ProtoMessage()    {}
func (*MsgClaimAirdrop) Descriptor() ([]byte, []int) {
	return fileDescriptor_df595e1582cd6fea, []int{0}
}
func (m *MsgClaimAirdrop) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAirdrop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAirdrop.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAirdrop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAirdrop.Merge(m, src)
}
func (m *MsgClaimAirdrop) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAirdrop) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAirdrop.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAirdrop proto.InternalMessageInfo

func (m *MsgClaimAirdrop) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

func (m *MsgClaimAirdrop) GetBtcAddressHash() []byte {
	if m != nil {
		return m.BtcAddressHash
	}
	return nil
}

func (m *MsgClaimAirdrop) GetProof() ZKProof {
	if m != nil {
		return m.Proof
	}
	return ZKProof{}
}

// MsgClaimAirdropResponse is the response for a successful airdrop claim.
type MsgClaimAirdropResponse struct {
	// The amount of tokens claimed
	AmountClaimed uint64 `protobuf:"varint,1,opt,name=amount_claimed,json=amountClaimed,proto3" json:"amount_claimed,omitempty"`
}

func (m *MsgClaimAirdropResponse) Reset()         { *m = MsgClaimAirdropResponse{} }
func (m *MsgClaimAirdropResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAirdropResponse) ProtoMessage()    {}
func (*MsgClaimAirdropResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df595e1582cd6fea, []int{1}
}
func (m *MsgClaimAirdropResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAirdropResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAirdropResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAirdropResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAirdropResponse.Merge(m, src)
}
func (m *MsgClaimAirdropResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAirdropResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAirdropResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAirdropResponse proto.InternalMessageInfo

func (m *MsgClaimAirdropResponse) GetAmountClaimed() uint64 {
	if m != nil {
		return m.AmountClaimed
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgClaimAirdrop)(nil), "qbtc.qbtc.v1.MsgClaimAirdrop")
	proto.RegisterType((*MsgClaimAirdropResponse)(nil), "qbtc.qbtc.v1.MsgClaimAirdropResponse")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/msg_claim_airdrop.proto", fileDescriptor_df595e1582cd6fea)
}

var fileDescriptor_df595e1582cd6fea = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0x31, 0x4f, 0xc2, 0x40,
	0x18, 0xed, 0x29, 0x6a, 0x3c, 0x11, 0xb5, 0xc1, 0xd0, 0x30, 0x14, 0x42, 0x24, 0x69, 0x48, 0x6c,
	0x83, 0x6e, 0x2e, 0x0a, 0x2c, 0x26, 0xc6, 0xc4, 0x74, 0x64, 0x69, 0xae, 0xd7, 0xda, 0x36, 0xb1,
	0x7c, 0xe5, 0xee, 0x20, 0xba, 0x3a, 0x3a, 0xf9, 0x4f, 0xe4, 0x67, 0x30, 0x32, 0x3a, 0x19, 0x03,
	0x03, 0x7f, 0xc3, 0xf4, 0x0e, 0x12, 0x61, 0xf9, 0xfa, 0xf5, 0xbd, 0x97, 0xef, 0xbd, 0x7b, 0xf8,
	0x62, 0xe8, 0x0b, 0xea, 0xc8, 0x31, 0x6e, 0x3b, 0x29, 0x8f, 0x3c, 0xfa, 0x42, 0x92, 0xd4, 0x23,
	0x09, 0x0b, 0x18, 0x64, 0x76, 0xc6, 0x40, 0x80, 0x5e, 0xcc, 0x05, 0xb6, 0x1c, 0xe3, 0x76, 0xf5,
	0x8c, 0xa4, 0xc9, 0x00, 0x1c, 0x39, 0x95, 0xa0, 0x5a, 0xa1, 0xc0, 0x53, 0xe0, 0xf9, 0x81, 0xd5,
	0x9d, 0x15, 0x51, 0x8e, 0x20, 0x02, 0xb9, 0x3a, 0xf9, 0xb6, 0x42, 0x6b, 0x1b, 0xae, 0xe2, 0x2d,
	0x0b, 0x37, 0x0d, 0x1b, 0x5f, 0x08, 0x9f, 0x3c, 0xf2, 0xa8, 0x97, 0x67, 0xe9, 0x28, 0x46, 0x37,
	0xf0, 0x81, 0xcc, 0x16, 0x32, 0x03, 0xd5, 0x91, 0x75, 0xe8, 0xae, 0x7f, 0x75, 0x0b, 0x9f, 0xfa,
	0x82, 0x7a, 0x24, 0x08, 0x58, 0xc8, 0xb9, 0x17, 0x13, 0x1e, 0x1b, 0x3b, 0x75, 0x64, 0x15, 0xdd,
	0x92, 0x2f, 0x68, 0x47, 0xc1, 0xf7, 0x84, 0xc7, 0x7a, 0x1b, 0xef, 0x65, 0x0c, 0xe0, 0xd9, 0xd8,
	0xad, 0x23, 0xeb, 0xe8, 0xea, 0xdc, 0xfe, 0xff, 0x30, 0xbb, 0xff, 0xf0, 0x94, 0x93, 0xdd, 0xc2,
	0xf4, 0xa7, 0xa6, 0xb9, 0x4a, 0x79, 0xd3, 0x7c, 0x5f, 0x4e, 0x5a, 0x6b, 0xab, 0x8f, 0xe5, 0xa4,
	0x55, 0x96, 0xb9, 0xb7, 0xd2, 0x35, 0xee, 0x70, 0x65, 0x0b, 0x72, 0x43, 0x9e, 0xc1, 0x80, 0x87,
	0x7a, 0x13, 0x97, 0x48, 0x0a, 0xa3, 0x81, 0x50, 0xdd, 0x86, 0x81, 0xcc, 0x5f, 0x70, 0x8f, 0x15,
	0xda, 0x53, 0x60, 0xf7, 0x76, 0x3a, 0x37, 0xd1, 0x6c, 0x6e, 0xa2, 0xdf, 0xb9, 0x89, 0x3e, 0x17,
	0xa6, 0x36, 0x5b, 0x98, 0xda, 0xf7, 0xc2, 0xd4, 0xfa, 0xcd, 0x28, 0x11, 0xf1, 0xc8, 0xb7, 0x29,
	0xa4, 0x8e, 0x2f, 0xe8, 0xf0, 0x12, 0x58, 0xa4, 0xda, 0x7b, 0x55, 0x9f, 0xbc, 0x41, 0xee, 0xef,
	0xcb, 0xee, 0xae, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x58, 0x65, 0x93, 0xd4, 0x01, 0x00,
	0x00,
}

func (m *MsgClaimAirdrop) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAirdrop) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAirdrop) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgClaimAirdrop(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.BtcAddressHash) > 0 {
		i -= len(m.BtcAddressHash)
		copy(dAtA[i:], m.BtcAddressHash)
		i = encodeVarintMsgClaimAirdrop(dAtA, i, uint64(len(m.BtcAddressHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintMsgClaimAirdrop(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimAirdropResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAirdropResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAirdropResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AmountClaimed != 0 {
		i = encodeVarintMsgClaimAirdrop(dAtA, i, uint64(m.AmountClaimed))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgClaimAirdrop(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgClaimAirdrop(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimAirdrop) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovMsgClaimAirdrop(uint64(l))
	}
	l = len(m.BtcAddressHash)
	if l > 0 {
		n += 1 + l + sovMsgClaimAirdrop(uint64(l))
	}
	l = m.Proof.Size()
	n += 1 + l + sovMsgClaimAirdrop(uint64(l))
	return n
}

func (m *MsgClaimAirdropResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AmountClaimed != 0 {
		n += 1 + sovMsgClaimAirdrop(uint64(m.AmountClaimed))
	}
	return n
}

func sovMsgClaimAirdrop(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgClaimAirdrop(x uint64) (n int) {
	return sovMsgClaimAirdrop(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimAirdrop) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgClaimAirdrop
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAirdrop: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAirdrop: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcAddressHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcAddressHash = append(m.BtcAddressHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BtcAddressHash == nil {
				m.BtcAddressHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgClaimAirdrop(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAirdropResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgClaimAirdrop
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAirdropResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAirdropResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountClaimed", wireType)
			}
			m.AmountClaimed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountClaimed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgClaimAirdrop(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgClaimAirdrop
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgClaimAirdrop(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgClaimAirdrop
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgClaimAirdrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgClaimAirdrop
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgClaimAirdrop
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgClaimAirdrop
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgClaimAirdrop        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgClaimAirdrop          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgClaimAirdrop = fmt.Errorf("proto: unexpected end of group")
)
