// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/msg_claim_with_proof.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UTXORef identifies a specific UTXO by its transaction ID and output index.
type UTXORef struct {
	// The Bitcoin transaction ID where this UTXO originates
	Txid string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	// The output index in the Bitcoin transaction
	Vout uint32 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
}

func (m *UTXORef) Reset()         { *m = UTXORef{} }
func (m *UTXORef) String() string { return proto.CompactTextString(m) }
func (*UTXORef) ProtoMessage()    {}
func (*UTXORef) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf71fdfb6b1ac5fe, []int{0}
}
func (m *UTXORef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UTXORef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UTXORef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UTXORef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTXORef.Merge(m, src)
}
func (m *UTXORef) XXX_Size() int {
	return m.Size()
}
func (m *UTXORef) XXX_DiscardUnknown() {
	xxx_messageInfo_UTXORef.DiscardUnknown(m)
}

var xxx_messageInfo_UTXORef proto.InternalMessageInfo

func (m *UTXORef) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *UTXORef) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

// MsgClaimWithProof is the message for claiming one or more UTXOs using a ZK
// proof. The user proves ownership of a Bitcoin address without revealing
// their private key. Only UTXOs belonging to the proven Bitcoin address will
// be claimed; others are skipped. Maximum 50 UTXOs can be claimed in a single
// batch to prevent DoS.
type MsgClaimWithProof struct {
	// The address on the qbtc chain that will receive the claimed tokens
	Claimer string `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	// The UTXOs to claim. Only those matching the proven Bitcoin address will
	// be claimed; others are skipped. Maximum 50 UTXOs per batch.
	Utxos []UTXORef `protobuf:"bytes,2,rep,name=utxos,proto3" json:"utxos"`
	// Hex-encoded ZK proof proving ownership of the Bitcoin address associated
	// with the UTXOs being claimed.
	Proof string `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	// hex encoded message hash
	MessageHash string `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	// hex encoded address hash
	AddressHash string `protobuf:"bytes,5,opt,name=address_hash,json=addressHash,proto3" json:"address_hash,omitempty"`
	// hex encoded qbtc address hash
	QbtcAddressHash string `protobuf:"bytes,6,opt,name=qbtc_address_hash,json=qbtcAddressHash,proto3" json:"qbtc_address_hash,omitempty"`
	// hex encoded SHA256 of the 33-byte SEC-compressed public key. This is a
	// public input to the ZK circuit; the handler natively verifies
	// RIPEMD160(pub_key_hash_sha256) matches the UTXO's Bitcoin address hash.
	PubKeyHashSha256 string `protobuf:"bytes,7,opt,name=pub_key_hash_sha256,json=pubKeyHashSha256,proto3" json:"pub_key_hash_sha256,omitempty"`
}

func (m *MsgClaimWithProof) Reset()         { *m = MsgClaimWithProof{} }
func (m *MsgClaimWithProof) String() string { return proto.CompactTextString(m) }
func (*MsgClaimWithProof) ProtoMessage()    {}
func (*MsgClaimWithProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf71fdfb6b1ac5fe, []int{1}
}
func (m *MsgClaimWithProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimWithProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimWithProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimWithProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimWithProof.Merge(m, src)
}
func (m *MsgClaimWithProof) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimWithProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimWithProof.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimWithProof proto.InternalMessageInfo

func (m *MsgClaimWithProof) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

func (m *MsgClaimWithProof) GetUtxos() []UTXORef {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *MsgClaimWithProof) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

func (m *MsgClaimWithProof) GetMessageHash() string {
	if m != nil {
		return m.MessageHash
	}
	return ""
}

func (m *MsgClaimWithProof) GetAddressHash() string {
	if m != nil {
		return m.AddressHash
	}
	return ""
}

func (m *MsgClaimWithProof) GetQbtcAddressHash() string {
	if m != nil {
		return m.QbtcAddressHash
	}
	return ""
}

func (m *MsgClaimWithProof) GetPubKeyHashSha256() string {
	if m != nil {
		return m.PubKeyHashSha256
	}
	return ""
}

// MsgClaimWithProofResponse is the response for a successful batch claim.
type MsgClaimWithProofResponse struct {
	// The total amount of tokens claimed across all UTXOs
	TotalAmountClaimed uint64 `protobuf:"varint,1,opt,name=total_amount_claimed,json=totalAmountClaimed,proto3" json:"total_amount_claimed,omitempty"`
	// The number of UTXOs successfully claimed
	UtxosClaimed uint32 `protobuf:"varint,2,opt,name=utxos_claimed,json=utxosClaimed,proto3" json:"utxos_claimed,omitempty"`
	// The number of UTXOs skipped (not matching the proven address)
	UtxosSkipped uint32 `protobuf:"varint,3,opt,name=utxos_skipped,json=utxosSkipped,proto3" json:"utxos_skipped,omitempty"`
}

func (m *MsgClaimWithProofResponse) Reset()         { *m = MsgClaimWithProofResponse{} }
func (m *MsgClaimWithProofResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimWithProofResponse) ProtoMessage()    {}
func (*MsgClaimWithProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf71fdfb6b1ac5fe, []int{2}
}
func (m *MsgClaimWithProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimWithProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimWithProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimWithProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimWithProofResponse.Merge(m, src)
}
func (m *MsgClaimWithProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimWithProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimWithProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimWithProofResponse proto.InternalMessageInfo

func (m *MsgClaimWithProofResponse) GetTotalAmountClaimed() uint64 {
	if m != nil {
		return m.TotalAmountClaimed
	}
	return 0
}

func (m *MsgClaimWithProofResponse) GetUtxosClaimed() uint32 {
	if m != nil {
		return m.UtxosClaimed
	}
	return 0
}

func (m *MsgClaimWithProofResponse) GetUtxosSkipped() uint32 {
	if m != nil {
		return m.UtxosSkipped
	}
	return 0
}

func init() {
	proto.RegisterType((*UTXORef)(nil), "qbtc.qbtc.v1.UTXORef")
	proto.RegisterType((*MsgClaimWithProof)(nil), "qbtc.qbtc.v1.MsgClaimWithProof")
	proto.RegisterType((*MsgClaimWithProofResponse)(nil), "qbtc.qbtc.v1.MsgClaimWithProofResponse")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/msg_claim_with_proof.proto", fileDescriptor_bf71fdfb6b1ac5fe)
}

var fileDescriptor_bf71fdfb6b1ac5fe = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0x34, 0x69, 0xc4, 0x35, 0x15, 0xe4, 0x08, 0x60, 0x3a, 0x98, 0x10, 0x84, 0x1a,
	0x45, 0xaa, 0x4d, 0x8a, 0x60, 0x60, 0x41, 0x6d, 0x17, 0x24, 0x84, 0x40, 0x2e, 0x08, 0xc4, 0x62,
	0x9d, 0xed, 0xab, 0x6d, 0xb5, 0xce, 0x5d, 0xfd, 0xce, 0x21, 0x59, 0x19, 0x99, 0xd8, 0xf8, 0x37,
	0xfa, 0x27, 0x30, 0x76, 0xec, 0xc8, 0x84, 0x50, 0x32, 0xf4, 0xdf, 0x40, 0xf7, 0xce, 0x41, 0x41,
	0x59, 0xce, 0xcf, 0xdf, 0xef, 0x47, 0xef, 0xee, 0xfd, 0x20, 0xbb, 0xe7, 0xa1, 0x8a, 0x3c, 0x3c,
	0x26, 0x23, 0x2f, 0x87, 0x24, 0x88, 0xce, 0x58, 0x96, 0x07, 0x5f, 0x32, 0x95, 0x06, 0xb2, 0x10,
	0xe2, 0xc4, 0x95, 0x85, 0x50, 0x82, 0xb6, 0x35, 0xe3, 0xe2, 0x31, 0x19, 0xed, 0x74, 0x58, 0x9e,
	0x8d, 0x85, 0x87, 0xa7, 0x01, 0x76, 0xee, 0x45, 0x02, 0x72, 0x01, 0x3a, 0x47, 0x95, 0xaa, 0x32,
	0xba, 0x89, 0x48, 0x04, 0x86, 0x9e, 0x8e, 0x8c, 0xda, 0x1f, 0x91, 0xd6, 0x87, 0xf7, 0x9f, 0xde,
	0xfa, 0xfc, 0x84, 0x52, 0xd2, 0x50, 0xd3, 0x2c, 0xb6, 0xad, 0x9e, 0x35, 0xb8, 0xe1, 0x63, 0xac,
	0xb5, 0x89, 0x28, 0x95, 0x5d, 0xef, 0x59, 0x83, 0x6d, 0x1f, 0xe3, 0xfe, 0xcf, 0x3a, 0xe9, 0xbc,
	0x81, 0xe4, 0x48, 0x3f, 0xf0, 0x63, 0xa6, 0xd2, 0x77, 0xfa, 0x79, 0xd4, 0x26, 0x2d, 0x7c, 0x32,
	0x2f, 0xaa, 0x04, 0xcb, 0x5f, 0x3a, 0x22, 0xcd, 0x52, 0x4d, 0x05, 0xd8, 0xf5, 0xde, 0xc6, 0x60,
	0x6b, 0xff, 0x8e, 0xbb, 0x5a, 0x82, 0x5b, 0xdd, 0x7e, 0xd8, 0xb8, 0xfc, 0xfd, 0xa0, 0xe6, 0x1b,
	0x92, 0x76, 0x49, 0x13, 0x8b, 0xb6, 0x37, 0x30, 0x95, 0xf9, 0xa1, 0x0f, 0x49, 0x3b, 0xe7, 0x00,
	0x2c, 0xe1, 0x41, 0xca, 0x20, 0xb5, 0x1b, 0x68, 0x6e, 0x55, 0xda, 0x2b, 0x06, 0xa9, 0x46, 0x58,
	0x1c, 0x17, 0x1c, 0xc0, 0x20, 0x4d, 0x83, 0x54, 0x1a, 0x22, 0x43, 0xd2, 0xd1, 0x77, 0x07, 0xff,
	0x71, 0x9b, 0xc8, 0xdd, 0xd4, 0xc6, 0xc1, 0x0a, 0xbb, 0x47, 0x6e, 0xcb, 0x32, 0x0c, 0x4e, 0xf9,
	0x0c, 0xb1, 0x00, 0x52, 0xb6, 0xff, 0xec, 0xb9, 0xdd, 0x42, 0xfa, 0x96, 0x2c, 0xc3, 0xd7, 0x7c,
	0xa6, 0xc1, 0x63, 0xd4, 0x5f, 0xec, 0x7e, 0xbd, 0xbe, 0x18, 0x2e, 0xeb, 0xfe, 0x76, 0x7d, 0x31,
	0xbc, 0x8b, 0x13, 0x5d, 0x6b, 0x56, 0xff, 0x87, 0x45, 0xee, 0xaf, 0xa9, 0x3e, 0x07, 0x29, 0xc6,
	0xc0, 0xe9, 0x13, 0xd2, 0x55, 0x42, 0xb1, 0xb3, 0x80, 0xe5, 0xa2, 0x1c, 0x2b, 0xb3, 0x0a, 0xdc,
	0x0c, 0xa6, 0xe1, 0x53, 0xf4, 0x0e, 0xd0, 0x3a, 0x32, 0x0e, 0x7d, 0x44, 0xb6, 0xb1, 0x71, 0xff,
	0x50, 0x33, 0xaf, 0x36, 0x8a, 0x6b, 0x10, 0x9c, 0x66, 0x52, 0xf2, 0x18, 0x9b, 0xbb, 0x84, 0x8e,
	0x8d, 0x76, 0xf8, 0xf2, 0x72, 0xee, 0x58, 0x57, 0x73, 0xc7, 0xfa, 0x33, 0x77, 0xac, 0xef, 0x0b,
	0xa7, 0x76, 0xb5, 0x70, 0x6a, 0xbf, 0x16, 0x4e, 0xed, 0xf3, 0xe3, 0x24, 0x53, 0x69, 0x19, 0xba,
	0x91, 0xc8, 0xbd, 0x50, 0x45, 0xe7, 0x7b, 0xa2, 0x48, 0xcc, 0xc6, 0x4e, 0xcd, 0x47, 0xcd, 0x24,
	0x87, 0x70, 0x13, 0xf7, 0xea, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x83, 0x52, 0x42,
	0xd2, 0x02, 0x00, 0x00,
}

func (m *UTXORef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UTXORef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UTXORef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Vout != 0 {
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(m.Vout))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Txid) > 0 {
		i -= len(m.Txid)
		copy(dAtA[i:], m.Txid)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.Txid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimWithProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimWithProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimWithProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKeyHashSha256) > 0 {
		i -= len(m.PubKeyHashSha256)
		copy(dAtA[i:], m.PubKeyHashSha256)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.PubKeyHashSha256)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.QbtcAddressHash) > 0 {
		i -= len(m.QbtcAddressHash)
		copy(dAtA[i:], m.QbtcAddressHash)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.QbtcAddressHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AddressHash) > 0 {
		i -= len(m.AddressHash)
		copy(dAtA[i:], m.AddressHash)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.AddressHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MessageHash) > 0 {
		i -= len(m.MessageHash)
		copy(dAtA[i:], m.MessageHash)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.MessageHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Utxos) > 0 {
		for iNdEx := len(m.Utxos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Utxos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimWithProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimWithProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimWithProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UtxosSkipped != 0 {
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(m.UtxosSkipped))
		i--
		dAtA[i] = 0x18
	}
	if m.UtxosClaimed != 0 {
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(m.UtxosClaimed))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalAmountClaimed != 0 {
		i = encodeVarintMsgClaimWithProof(dAtA, i, uint64(m.TotalAmountClaimed))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgClaimWithProof(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgClaimWithProof(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UTXORef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Txid)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	if m.Vout != 0 {
		n += 1 + sovMsgClaimWithProof(uint64(m.Vout))
	}
	return n
}

func (m *MsgClaimWithProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	if len(m.Utxos) > 0 {
		for _, e := range m.Utxos {
			l = e.Size()
			n += 1 + l + sovMsgClaimWithProof(uint64(l))
		}
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	l = len(m.MessageHash)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	l = len(m.AddressHash)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	l = len(m.QbtcAddressHash)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	l = len(m.PubKeyHashSha256)
	if l > 0 {
		n += 1 + l + sovMsgClaimWithProof(uint64(l))
	}
	return n
}

func (m *MsgClaimWithProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalAmountClaimed != 0 {
		n += 1 + sovMsgClaimWithProof(uint64(m.TotalAmountClaimed))
	}
	if m.UtxosClaimed != 0 {
		n += 1 + sovMsgClaimWithProof(uint64(m.UtxosClaimed))
	}
	if m.UtxosSkipped != 0 {
		n += 1 + sovMsgClaimWithProof(uint64(m.UtxosSkipped))
	}
	return n
}

func sovMsgClaimWithProof(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgClaimWithProof(x uint64) (n int) {
	return sovMsgClaimWithProof(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UTXORef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgClaimWithProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UTXORef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UTXORef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vout", wireType)
			}
			m.Vout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgClaimWithProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimWithProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgClaimWithProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimWithProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimWithProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utxos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Utxos = append(m.Utxos, UTXORef{})
			if err := m.Utxos[len(m.Utxos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QbtcAddressHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QbtcAddressHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeyHashSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeyHashSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgClaimWithProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimWithProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgClaimWithProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimWithProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimWithProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmountClaimed", wireType)
			}
			m.TotalAmountClaimed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalAmountClaimed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UtxosClaimed", wireType)
			}
			m.UtxosClaimed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UtxosClaimed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UtxosSkipped", wireType)
			}
			m.UtxosSkipped = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UtxosSkipped |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgClaimWithProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgClaimWithProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgClaimWithProof(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgClaimWithProof
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgClaimWithProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgClaimWithProof
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgClaimWithProof
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgClaimWithProof
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgClaimWithProof        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgClaimWithProof          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgClaimWithProof = fmt.Errorf("proto: unexpected end of group")
)
