// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/msg_report_block.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Attestation struct {
	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_628d11da7ff97b80, []int{0}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return m.Size()
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

type MsgBtcBlock struct {
	// The height of the reported Bitcoin block
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// The hash of the reported Bitcoin block
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// compressed bytes of BTC block
	BlockContent []byte         `protobuf:"bytes,3,opt,name=block_content,json=blockContent,proto3" json:"block_content,omitempty"`
	Attestations []*Attestation `protobuf:"bytes,4,rep,name=attestations,proto3" json:"attestations,omitempty"`
	Signer       string         `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgBtcBlock) Reset()         { *m = MsgBtcBlock{} }
func (m *MsgBtcBlock) String() string { return proto.CompactTextString(m) }
func (*MsgBtcBlock) ProtoMessage()    {}
func (*MsgBtcBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_628d11da7ff97b80, []int{1}
}
func (m *MsgBtcBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBtcBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBtcBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBtcBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBtcBlock.Merge(m, src)
}
func (m *MsgBtcBlock) XXX_Size() int {
	return m.Size()
}
func (m *MsgBtcBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBtcBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBtcBlock proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Attestation)(nil), "qbtc.qbtc.v1.Attestation")
	proto.RegisterType((*MsgBtcBlock)(nil), "qbtc.qbtc.v1.MsgBtcBlock")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/msg_report_block.proto", fileDescriptor_628d11da7ff97b80)
}

var fileDescriptor_628d11da7ff97b80 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3f, 0xcf, 0xd2, 0x40,
	0x18, 0xef, 0xf9, 0x22, 0x86, 0xa3, 0x26, 0x7a, 0x79, 0xa3, 0x7d, 0x89, 0xb9, 0x34, 0x10, 0x13,
	0x42, 0x42, 0x2b, 0xb8, 0x99, 0x38, 0x50, 0x47, 0xe3, 0x52, 0x36, 0x97, 0xa6, 0x2d, 0x97, 0x6b,
	0xa3, 0xed, 0xc1, 0xdd, 0x03, 0xd1, 0xcd, 0x38, 0x3a, 0xf9, 0x51, 0x18, 0xfc, 0x10, 0x8c, 0xc4,
	0x89, 0x51, 0xca, 0xc0, 0xec, 0x37, 0x30, 0xbd, 0xab, 0x01, 0x27, 0x97, 0xa7, 0xf7, 0xfb, 0xd3,
	0x5f, 0xf3, 0x7b, 0x7a, 0x78, 0xb0, 0x4a, 0x20, 0xf5, 0xf5, 0xd8, 0x4c, 0xfc, 0x42, 0xf1, 0x48,
	0xb2, 0xa5, 0x90, 0x10, 0x25, 0x1f, 0x45, 0xfa, 0xc1, 0x5b, 0x4a, 0x01, 0x82, 0xd8, 0xb5, 0xee,
	0xe9, 0xb1, 0x99, 0xf4, 0x1e, 0xc7, 0x45, 0x5e, 0x0a, 0x5f, 0x4f, 0x63, 0xe8, 0x3d, 0x4d, 0x85,
	0x2a, 0x84, 0xaa, 0xdf, 0x6f, 0x62, 0x1a, 0xe1, 0xce, 0x08, 0x91, 0x46, 0xbe, 0x01, 0x8d, 0x74,
	0xcb, 0x05, 0x17, 0x86, 0xaf, 0x4f, 0x86, 0xed, 0x47, 0xb8, 0x3b, 0x03, 0x60, 0x0a, 0x62, 0xc8,
	0x45, 0x49, 0xa6, 0xf8, 0x41, 0xbc, 0x58, 0x48, 0xa6, 0x94, 0x83, 0x5c, 0x34, 0xec, 0x04, 0xce,
	0xcf, 0x1f, 0xe3, 0xdb, 0x26, 0x67, 0x66, 0x94, 0x39, 0xc8, 0xbc, 0xe4, 0xe1, 0x5f, 0x23, 0x79,
	0x86, 0x3b, 0xf3, 0x9c, 0x97, 0x31, 0xac, 0x25, 0x73, 0xee, 0xb9, 0x68, 0x68, 0x87, 0x17, 0xa2,
	0xff, 0x1b, 0xe1, 0xee, 0x3b, 0xc5, 0x03, 0x48, 0x83, 0xba, 0x21, 0x79, 0x82, 0xdb, 0x19, 0xcb,
	0x79, 0x06, 0xfa, 0x03, 0xad, 0xb0, 0x41, 0x84, 0xe0, 0x56, 0x16, 0xab, 0x4c, 0x07, 0x74, 0x42,
	0x7d, 0x26, 0x03, 0xfc, 0x50, 0xaf, 0x25, 0x4a, 0x45, 0x09, 0xac, 0x04, 0xe7, 0x46, 0xa7, 0xdb,
	0x9a, 0x7c, 0x63, 0x38, 0xf2, 0x1a, 0xdb, 0xf1, 0xa5, 0x81, 0x72, 0x5a, 0xee, 0xcd, 0xb0, 0x3b,
	0xbd, 0xf3, 0xae, 0x77, 0xe8, 0x5d, 0x75, 0x0c, 0xff, 0xb1, 0x93, 0x17, 0xb8, 0xad, 0x72, 0x5e,
	0x32, 0xe9, 0xdc, 0xff, 0x4f, 0xe1, 0xc6, 0xf7, 0xca, 0xfd, 0x7a, 0xde, 0x8e, 0x1a, 0xf0, 0xed,
	0xbc, 0x1d, 0x3d, 0x4a, 0x20, 0x5d, 0xf9, 0x57, 0x1d, 0x83, 0xb7, 0xbb, 0x23, 0xb5, 0x0e, 0x47,
	0x8a, 0xbe, 0x54, 0xd4, 0xda, 0x55, 0x14, 0xed, 0x2b, 0x8a, 0x7e, 0x55, 0x14, 0x7d, 0x3f, 0x51,
	0x6b, 0x7f, 0xa2, 0xd6, 0xe1, 0x44, 0xad, 0xf7, 0xcf, 0x79, 0x0e, 0xd9, 0x3a, 0xf1, 0x52, 0x51,
	0xf8, 0x75, 0xc4, 0x58, 0x48, 0x6e, 0x6e, 0xc6, 0x27, 0xf3, 0x80, 0xcf, 0x4b, 0xa6, 0x92, 0xb6,
	0xfe, 0x51, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xea, 0xf9, 0xd8, 0xa3, 0x3a, 0x02, 0x00,
	0x00,
}

func (m *Attestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBtcBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBtcBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBtcBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgReportBlock(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.BlockContent) > 0 {
		i -= len(m.BlockContent)
		copy(dAtA[i:], m.BlockContent)
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(len(m.BlockContent)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintMsgReportBlock(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgReportBlock(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgReportBlock(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Attestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMsgReportBlock(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovMsgReportBlock(uint64(l))
	}
	return n
}

func (m *MsgBtcBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovMsgReportBlock(uint64(m.Height))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovMsgReportBlock(uint64(l))
	}
	l = len(m.BlockContent)
	if l > 0 {
		n += 1 + l + sovMsgReportBlock(uint64(l))
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovMsgReportBlock(uint64(l))
		}
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgReportBlock(uint64(l))
	}
	return n
}

func sovMsgReportBlock(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgReportBlock(x uint64) (n int) {
	return sovMsgReportBlock(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Attestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgReportBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgReportBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBtcBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgReportBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBtcBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBtcBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockContent", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockContent = append(m.BlockContent[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockContent == nil {
				m.BlockContent = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, &Attestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgReportBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgReportBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgReportBlock(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgReportBlock
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgReportBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgReportBlock
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgReportBlock
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgReportBlock
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgReportBlock        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgReportBlock          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgReportBlock = fmt.Errorf("proto: unexpected end of group")
)
