// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("qbtc/qbtc/v1/query.proto", fileDescriptor_73732787b77b750d) }

var fileDescriptor_73732787b77b750d = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0x33, 0x31,
	0x14, 0x85, 0xdb, 0x1f, 0xfe, 0x82, 0xc1, 0x8d, 0x83, 0x0b, 0x29, 0x12, 0x2b, 0xb6, 0x1b, 0xc1,
	0x09, 0xa3, 0x0f, 0x20, 0x75, 0xe7, 0xa2, 0x52, 0x5d, 0x08, 0xba, 0x29, 0xc9, 0x34, 0xc4, 0xc0,
	0x4c, 0x6e, 0x66, 0x92, 0x16, 0xfb, 0x16, 0x3e, 0x96, 0xcb, 0x2e, 0xbb, 0x94, 0xce, 0x8b, 0xc8,
	0x24, 0x29, 0x2a, 0x0e, 0xe3, 0xe6, 0x26, 0x9c, 0xf3, 0xdd, 0xc3, 0x09, 0x41, 0x47, 0x05, 0xb3,
	0x29, 0x71, 0x63, 0x99, 0x90, 0x62, 0xc1, 0xcb, 0x55, 0xac, 0x4b, 0xb0, 0x10, 0xed, 0xd7, 0x62,
	0xec, 0xc6, 0x32, 0xe9, 0x1f, 0xd0, 0x5c, 0x2a, 0x20, 0x6e, 0x7a, 0xa0, 0x7f, 0x9e, 0x82, 0xc9,
	0xc1, 0x10, 0x46, 0x0d, 0xf7, 0x9b, 0x64, 0x99, 0x30, 0x6e, 0x69, 0x42, 0x34, 0x15, 0x52, 0x51,
	0x2b, 0x41, 0x05, 0xf6, 0x50, 0x80, 0x00, 0x77, 0x25, 0xf5, 0x2d, 0xa8, 0xc7, 0x02, 0x40, 0x64,
	0x9c, 0x50, 0x2d, 0x09, 0x55, 0x0a, 0xac, 0x5b, 0x31, 0xc1, 0x1d, 0xfc, 0xae, 0x36, 0x53, 0x30,
	0xe7, 0x33, 0xa9, 0x03, 0x71, 0xd2, 0x40, 0x68, 0x5a, 0xd2, 0x3c, 0x44, 0x5c, 0x6e, 0xfe, 0xa1,
	0xff, 0xf7, 0xb5, 0x1c, 0x4d, 0x50, 0xef, 0x0e, 0xe6, 0xfc, 0x76, 0x1a, 0x0d, 0xe2, 0xef, 0x0f,
	0x8b, 0x9d, 0xed, 0xad, 0x07, 0x5e, 0x2c, 0xb8, 0xb1, 0xfd, 0xd3, 0x16, 0xc2, 0x68, 0x50, 0x86,
	0x47, 0x4f, 0x08, 0x8d, 0xb3, 0xcc, 0x8b, 0x26, 0x1a, 0x36, 0x2c, 0x7c, 0xd9, 0xbb, 0xd8, 0xd1,
	0x1f, 0x54, 0x88, 0x9e, 0xa0, 0xde, 0xd4, 0xbd, 0xa1, 0xb1, 0xa9, 0xb7, 0xda, 0x9a, 0xee, 0x88,
	0x10, 0xf7, 0x88, 0xf6, 0xc6, 0x59, 0x16, 0x12, 0xcf, 0x9a, 0x2b, 0xfc, 0x0c, 0x1d, 0xb6, 0x43,
	0x3e, 0xf7, 0xe6, 0xfa, 0x7d, 0x8b, 0xbb, 0xeb, 0x2d, 0xee, 0x7e, 0x6c, 0x71, 0xf7, 0xad, 0xc2,
	0x9d, 0x75, 0x85, 0x3b, 0x9b, 0x0a, 0x77, 0x9e, 0x47, 0x42, 0xda, 0x97, 0x05, 0x8b, 0x53, 0xc8,
	0x09, 0xb3, 0x69, 0x71, 0x01, 0xa5, 0xf0, 0x9f, 0xf4, 0xea, 0x0f, 0xbb, 0xd2, 0xdc, 0xb0, 0x9e,
	0xfb, 0xa2, 0xab, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x0e, 0x66, 0xb3, 0x82, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// NodeIP returns the IP address of the node.
	NodeIP(ctx context.Context, in *QueryNodeIPRequest, opts ...grpc.CallOption) (*QueryNodeIPResponse, error)
	// AllNodeIPs returns all the IP addresses of the nodes.
	AllNodeIPs(ctx context.Context, in *QueryAllNodeIPsRequest, opts ...grpc.CallOption) (*QueryAllNodeIPsResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	AllParams(ctx context.Context, in *QueryAllParamsRequest, opts ...grpc.CallOption) (*QueryAllParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) NodeIP(ctx context.Context, in *QueryNodeIPRequest, opts ...grpc.CallOption) (*QueryNodeIPResponse, error) {
	out := new(QueryNodeIPResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/NodeIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllNodeIPs(ctx context.Context, in *QueryAllNodeIPsRequest, opts ...grpc.CallOption) (*QueryAllNodeIPsResponse, error) {
	out := new(QueryAllNodeIPsResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/AllNodeIPs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllParams(ctx context.Context, in *QueryAllParamsRequest, opts ...grpc.CallOption) (*QueryAllParamsResponse, error) {
	out := new(QueryAllParamsResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/AllParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// NodeIP returns the IP address of the node.
	NodeIP(context.Context, *QueryNodeIPRequest) (*QueryNodeIPResponse, error)
	// AllNodeIPs returns all the IP addresses of the nodes.
	AllNodeIPs(context.Context, *QueryAllNodeIPsRequest) (*QueryAllNodeIPsResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	AllParams(context.Context, *QueryAllParamsRequest) (*QueryAllParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) NodeIP(ctx context.Context, req *QueryNodeIPRequest) (*QueryNodeIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeIP not implemented")
}
func (*UnimplementedQueryServer) AllNodeIPs(ctx context.Context, req *QueryAllNodeIPsRequest) (*QueryAllNodeIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllNodeIPs not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AllParams(ctx context.Context, req *QueryAllParamsRequest) (*QueryAllParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_NodeIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodeIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NodeIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/NodeIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NodeIP(ctx, req.(*QueryNodeIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllNodeIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNodeIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllNodeIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/AllNodeIPs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllNodeIPs(ctx, req.(*QueryAllNodeIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/AllParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllParams(ctx, req.(*QueryAllParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qbtc.qbtc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeIP",
			Handler:    _Query_NodeIP_Handler,
		},
		{
			MethodName: "AllNodeIPs",
			Handler:    _Query_AllNodeIPs_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AllParams",
			Handler:    _Query_AllParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qbtc/qbtc/v1/query.proto",
}
