// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/query_node_ip.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryNodeIPRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryNodeIPRequest) Reset()         { *m = QueryNodeIPRequest{} }
func (m *QueryNodeIPRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNodeIPRequest) ProtoMessage()    {}
func (*QueryNodeIPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec91afcf1405218, []int{0}
}
func (m *QueryNodeIPRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNodeIPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNodeIPRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNodeIPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNodeIPRequest.Merge(m, src)
}
func (m *QueryNodeIPRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNodeIPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNodeIPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNodeIPRequest proto.InternalMessageInfo

func (m *QueryNodeIPRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAllNodeIPsRequest struct {
}

func (m *QueryAllNodeIPsRequest) Reset()         { *m = QueryAllNodeIPsRequest{} }
func (m *QueryAllNodeIPsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNodeIPsRequest) ProtoMessage()    {}
func (*QueryAllNodeIPsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec91afcf1405218, []int{1}
}
func (m *QueryAllNodeIPsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNodeIPsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNodeIPsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNodeIPsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNodeIPsRequest.Merge(m, src)
}
func (m *QueryAllNodeIPsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNodeIPsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNodeIPsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNodeIPsRequest proto.InternalMessageInfo

type QueryNodeIPResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IP      string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *QueryNodeIPResponse) Reset()         { *m = QueryNodeIPResponse{} }
func (m *QueryNodeIPResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNodeIPResponse) ProtoMessage()    {}
func (*QueryNodeIPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec91afcf1405218, []int{2}
}
func (m *QueryNodeIPResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNodeIPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNodeIPResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNodeIPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNodeIPResponse.Merge(m, src)
}
func (m *QueryNodeIPResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNodeIPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNodeIPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNodeIPResponse proto.InternalMessageInfo

func (m *QueryNodeIPResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryNodeIPResponse) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type QueryAllNodeIPsResponse struct {
	NodeIPs []*QueryNodeIPResponse `protobuf:"bytes,1,rep,name=node_ips,json=nodeIps,proto3" json:"node_ips,omitempty"`
}

func (m *QueryAllNodeIPsResponse) Reset()         { *m = QueryAllNodeIPsResponse{} }
func (m *QueryAllNodeIPsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNodeIPsResponse) ProtoMessage()    {}
func (*QueryAllNodeIPsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec91afcf1405218, []int{3}
}
func (m *QueryAllNodeIPsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNodeIPsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNodeIPsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNodeIPsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNodeIPsResponse.Merge(m, src)
}
func (m *QueryAllNodeIPsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNodeIPsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNodeIPsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNodeIPsResponse proto.InternalMessageInfo

func (m *QueryAllNodeIPsResponse) GetNodeIPs() []*QueryNodeIPResponse {
	if m != nil {
		return m.NodeIPs
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryNodeIPRequest)(nil), "qbtc.qbtc.v1.QueryNodeIPRequest")
	proto.RegisterType((*QueryAllNodeIPsRequest)(nil), "qbtc.qbtc.v1.QueryAllNodeIPsRequest")
	proto.RegisterType((*QueryNodeIPResponse)(nil), "qbtc.qbtc.v1.QueryNodeIPResponse")
	proto.RegisterType((*QueryAllNodeIPsResponse)(nil), "qbtc.qbtc.v1.QueryAllNodeIPsResponse")
}

func init() { proto.RegisterFile("qbtc/qbtc/v1/query_node_ip.proto", fileDescriptor_4ec91afcf1405218) }

var fileDescriptor_4ec91afcf1405218 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x4c, 0x2a, 0x49,
	0xd6, 0x07, 0x13, 0x65, 0x86, 0xfa, 0x85, 0xa5, 0xa9, 0x45, 0x95, 0xf1, 0x79, 0xf9, 0x29, 0xa9,
	0xf1, 0x99, 0x05, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x20, 0x49, 0x3d, 0x30, 0x51,
	0x66, 0x28, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x96, 0xd0, 0x07, 0xb1, 0x20, 0x6a, 0x94, 0xf4,
	0xb8, 0x84, 0x02, 0x41, 0x5a, 0xfd, 0xf2, 0x53, 0x52, 0x3d, 0x03, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8, 0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x09, 0x2e, 0x31, 0xb0, 0x7a, 0xc7, 0x9c, 0x1c, 0x88,
	0x96, 0x62, 0xa8, 0x1e, 0x25, 0x77, 0x2e, 0x61, 0x14, 0x93, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x71, 0x1b, 0x25, 0x24, 0xc6, 0xc5, 0x94, 0x59, 0x20, 0xc1, 0x04, 0x12, 0x74, 0x62, 0x7b, 0x74,
	0x4f, 0x9e, 0xc9, 0x33, 0x20, 0x88, 0x29, 0xb3, 0x40, 0x29, 0x85, 0x4b, 0x1c, 0xc3, 0x0a, 0xa8,
	0x61, 0x9e, 0x5c, 0x1c, 0x50, 0x2f, 0x82, 0x4c, 0x63, 0xd6, 0xe0, 0x36, 0x52, 0xd4, 0x43, 0xf6,
	0xa4, 0x1e, 0x16, 0x17, 0x38, 0x71, 0x3f, 0xba, 0x27, 0xcf, 0x0e, 0x33, 0x89, 0x1d, 0xa4, 0xdf,
	0xb3, 0xa0, 0xd8, 0xc9, 0xfe, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92,
	0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x54,
	0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93, 0x4a, 0x92, 0x0b, 0x75,
	0xf3, 0x8b, 0xd2, 0x21, 0xe1, 0x5c, 0x01, 0xa1, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0,
	0x01, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x62, 0x04, 0x98, 0x88, 0x01, 0x00, 0x00,
}

func (m *QueryNodeIPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNodeIPRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNodeIPRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQueryNodeIp(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNodeIPsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNodeIPsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNodeIPsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryNodeIPResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNodeIPResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNodeIPResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IP) > 0 {
		i -= len(m.IP)
		copy(dAtA[i:], m.IP)
		i = encodeVarintQueryNodeIp(dAtA, i, uint64(len(m.IP)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQueryNodeIp(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNodeIPsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNodeIPsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNodeIPsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeIPs) > 0 {
		for iNdEx := len(m.NodeIPs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeIPs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryNodeIp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryNodeIp(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryNodeIp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryNodeIPRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQueryNodeIp(uint64(l))
	}
	return n
}

func (m *QueryAllNodeIPsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryNodeIPResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQueryNodeIp(uint64(l))
	}
	l = len(m.IP)
	if l > 0 {
		n += 1 + l + sovQueryNodeIp(uint64(l))
	}
	return n
}

func (m *QueryAllNodeIPsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NodeIPs) > 0 {
		for _, e := range m.NodeIPs {
			l = e.Size()
			n += 1 + l + sovQueryNodeIp(uint64(l))
		}
	}
	return n
}

func sovQueryNodeIp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryNodeIp(x uint64) (n int) {
	return sovQueryNodeIp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryNodeIPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryNodeIp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNodeIPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNodeIPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryNodeIp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNodeIPsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryNodeIp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNodeIPsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNodeIPsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQueryNodeIp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNodeIPResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryNodeIp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNodeIPResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNodeIPResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryNodeIp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNodeIPsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryNodeIp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNodeIPsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNodeIPsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeIPs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeIPs = append(m.NodeIPs, &QueryNodeIPResponse{})
			if err := m.NodeIPs[len(m.NodeIPs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryNodeIp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryNodeIp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryNodeIp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryNodeIp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryNodeIp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryNodeIp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryNodeIp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryNodeIp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryNodeIp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryNodeIp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryNodeIp = fmt.Errorf("proto: unexpected end of group")
)
