// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("qbtc/qbtc/v1/query.proto", fileDescriptor_73732787b77b750d) }

var fileDescriptor_73732787b77b750d = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xe3, 0x40,
	0x18, 0xc7, 0x9b, 0x65, 0xb7, 0xb0, 0x61, 0xa1, 0x74, 0xe8, 0xd2, 0xa5, 0x74, 0xb3, 0xab, 0xb6,
	0x82, 0x45, 0x33, 0x44, 0x1f, 0x40, 0xea, 0x03, 0x48, 0xf5, 0xe8, 0xa5, 0x4c, 0x92, 0x8f, 0x18,
	0x4c, 0xf2, 0x25, 0x99, 0x69, 0xb1, 0x94, 0x5e, 0x7c, 0x02, 0x41, 0xf0, 0x26, 0xbe, 0x8e, 0xc7,
	0x82, 0x17, 0x8f, 0xd2, 0xfa, 0x20, 0xd2, 0xc9, 0xb4, 0xd8, 0x1a, 0x4b, 0x2f, 0x93, 0x8f, 0x6f,
	0x7e, 0xdf, 0xfc, 0xfe, 0x93, 0x44, 0xff, 0x93, 0xd8, 0xc2, 0xa1, 0x72, 0xe9, 0x5b, 0x34, 0xe9,
	0x41, 0x3a, 0x30, 0xe3, 0x14, 0x05, 0x92, 0x5f, 0xb3, 0xa6, 0x29, 0x97, 0xbe, 0x55, 0x2b, 0xb3,
	0xd0, 0x8f, 0x90, 0xca, 0x35, 0x03, 0x6a, 0x2d, 0x07, 0x79, 0x88, 0x9c, 0xda, 0x8c, 0x43, 0x36,
	0x49, 0xfb, 0x96, 0x0d, 0x82, 0x59, 0x34, 0x66, 0x9e, 0x1f, 0x31, 0xe1, 0x63, 0xa4, 0xd8, 0x8a,
	0x87, 0x1e, 0xca, 0x92, 0xce, 0x2a, 0xd5, 0xad, 0x7b, 0x88, 0x5e, 0x00, 0x94, 0xc5, 0x3e, 0x65,
	0x51, 0x84, 0x42, 0x8e, 0x70, 0xb5, 0xdb, 0xfc, 0x1c, 0xad, 0x1b, 0x03, 0xa4, 0x5d, 0xe6, 0xba,
	0x29, 0xf0, 0x39, 0xf6, 0x2f, 0x0f, 0x63, 0x29, 0x0b, 0x15, 0x70, 0xf8, 0xf8, 0x5d, 0xff, 0x71,
	0x36, 0x6b, 0x93, 0x7b, 0x4d, 0x2f, 0x9d, 0xa2, 0x0b, 0x1d, 0x80, 0xb4, 0x9d, 0x1d, 0x42, 0xf6,
	0xcc, 0x8f, 0xf7, 0x34, 0x25, 0xb8, 0xc2, 0x9c, 0x43, 0xd2, 0x03, 0x2e, 0x6a, 0xad, 0x4d, 0x50,
	0x1e, 0x63, 0xc4, 0x61, 0x7b, 0xff, 0xe6, 0xf9, 0xed, 0xee, 0xdb, 0x2e, 0x69, 0x2c, 0x92, 0x45,
	0xe8, 0xc2, 0x52, 0x7e, 0x3a, 0x54, 0xc5, 0x88, 0x3c, 0x68, 0x7a, 0xa5, 0x1d, 0x04, 0x2b, 0x87,
	0x01, 0x27, 0x66, 0x8e, 0x32, 0x0f, 0x9c, 0x47, 0xa4, 0x1b, 0xf3, 0x2a, 0x67, 0x43, 0xe6, 0x34,
	0x48, 0xfd, 0xeb, 0x9c, 0xc0, 0x49, 0xa0, 0x17, 0x3b, 0xf2, 0x95, 0x92, 0xff, 0x39, 0x82, 0x6c,
	0x6b, 0x1e, 0x61, 0x6b, 0x0d, 0xa1, 0xa4, 0x7f, 0xa5, 0xb4, 0x4a, 0x7e, 0x2f, 0xa4, 0xd9, 0x07,
	0xa3, 0xc3, 0x2b, 0x18, 0x8c, 0x08, 0xea, 0x3f, 0xdb, 0x41, 0xa0, 0x84, 0x3b, 0xf9, 0x37, 0x5a,
	0x76, 0x36, 0xd6, 0x43, 0x4a, 0x5b, 0x95, 0xda, 0x32, 0x29, 0xad, 0x68, 0x4f, 0x8e, 0x9f, 0x26,
	0x86, 0x36, 0x9e, 0x18, 0xda, 0xeb, 0xc4, 0xd0, 0x6e, 0xa7, 0x46, 0x61, 0x3c, 0x35, 0x0a, 0x2f,
	0x53, 0xa3, 0x70, 0xd1, 0xf4, 0x7c, 0x71, 0xd9, 0xb3, 0x4d, 0x07, 0x43, 0x6a, 0x0b, 0x27, 0x39,
	0xc0, 0xd4, 0xcb, 0xa6, 0xaf, 0xb3, 0x87, 0x18, 0xc4, 0xc0, 0xed, 0xa2, 0xfc, 0xd3, 0x8e, 0xde,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xfd, 0xec, 0xdb, 0x4e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// NodePeerAddress returns the peer address of the node.
	NodePeerAddress(ctx context.Context, in *QueryNodePeerAddressRequest, opts ...grpc.CallOption) (*QueryNodePeerAddressResponse, error)
	// AllNodePeerAddresses returns all the peer addresses of the nodes.
	AllNodePeerAddresses(ctx context.Context, in *QueryAllNodePeerAddressesRequest, opts ...grpc.CallOption) (*QueryAllNodePeerAddressesResponse, error)
	// Params returns the parameter for a specific key.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// AllParams returns all parameters in the qbtc module.
	AllParams(ctx context.Context, in *QueryAllParamsRequest, opts ...grpc.CallOption) (*QueryAllParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) NodePeerAddress(ctx context.Context, in *QueryNodePeerAddressRequest, opts ...grpc.CallOption) (*QueryNodePeerAddressResponse, error) {
	out := new(QueryNodePeerAddressResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/NodePeerAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllNodePeerAddresses(ctx context.Context, in *QueryAllNodePeerAddressesRequest, opts ...grpc.CallOption) (*QueryAllNodePeerAddressesResponse, error) {
	out := new(QueryAllNodePeerAddressesResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/AllNodePeerAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllParams(ctx context.Context, in *QueryAllParamsRequest, opts ...grpc.CallOption) (*QueryAllParamsResponse, error) {
	out := new(QueryAllParamsResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Query/AllParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// NodePeerAddress returns the peer address of the node.
	NodePeerAddress(context.Context, *QueryNodePeerAddressRequest) (*QueryNodePeerAddressResponse, error)
	// AllNodePeerAddresses returns all the peer addresses of the nodes.
	AllNodePeerAddresses(context.Context, *QueryAllNodePeerAddressesRequest) (*QueryAllNodePeerAddressesResponse, error)
	// Params returns the parameter for a specific key.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// AllParams returns all parameters in the qbtc module.
	AllParams(context.Context, *QueryAllParamsRequest) (*QueryAllParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) NodePeerAddress(ctx context.Context, req *QueryNodePeerAddressRequest) (*QueryNodePeerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodePeerAddress not implemented")
}
func (*UnimplementedQueryServer) AllNodePeerAddresses(ctx context.Context, req *QueryAllNodePeerAddressesRequest) (*QueryAllNodePeerAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllNodePeerAddresses not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AllParams(ctx context.Context, req *QueryAllParamsRequest) (*QueryAllParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_NodePeerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodePeerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NodePeerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/NodePeerAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NodePeerAddress(ctx, req.(*QueryNodePeerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllNodePeerAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNodePeerAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllNodePeerAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/AllNodePeerAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllNodePeerAddresses(ctx, req.(*QueryAllNodePeerAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Query/AllParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllParams(ctx, req.(*QueryAllParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qbtc.qbtc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodePeerAddress",
			Handler:    _Query_NodePeerAddress_Handler,
		},
		{
			MethodName: "AllNodePeerAddresses",
			Handler:    _Query_AllNodePeerAddresses_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AllParams",
			Handler:    _Query_AllParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qbtc/qbtc/v1/query.proto",
}
