// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/query_utxo.proto

package types

import (
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryUTXOsByAddressRequest requests UTXOs for a specific Bitcoin address.
type QueryUTXOsByAddressRequest struct {
	// btc_address is the Bitcoin address to query UTXOs for.
	BtcAddress string `protobuf:"bytes,1,opt,name=btc_address,json=btcAddress,proto3" json:"btc_address,omitempty"`
	// claimable, if true, restricts the result to UTXOs whose entitled_amount is
	// greater than zero (i.e. still claimable).
	Claimable bool `protobuf:"varint,2,opt,name=claimable,proto3" json:"claimable,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryUTXOsByAddressRequest) Reset()         { *m = QueryUTXOsByAddressRequest{} }
func (m *QueryUTXOsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUTXOsByAddressRequest) ProtoMessage()    {}
func (*QueryUTXOsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91cbbf8dfd8cd254, []int{0}
}
func (m *QueryUTXOsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUTXOsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUTXOsByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUTXOsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUTXOsByAddressRequest.Merge(m, src)
}
func (m *QueryUTXOsByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUTXOsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUTXOsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUTXOsByAddressRequest proto.InternalMessageInfo

func (m *QueryUTXOsByAddressRequest) GetBtcAddress() string {
	if m != nil {
		return m.BtcAddress
	}
	return ""
}

func (m *QueryUTXOsByAddressRequest) GetClaimable() bool {
	if m != nil {
		return m.Claimable
	}
	return false
}

func (m *QueryUTXOsByAddressRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryUTXOsByAddressResponse contains the UTXOs for the requested Bitcoin
// address.
type QueryUTXOsByAddressResponse struct {
	// utxos is the list of UTXOs matching the Bitcoin address.
	Utxos []UTXO `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos"`
	// pagination is the pagination response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryUTXOsByAddressResponse) Reset()         { *m = QueryUTXOsByAddressResponse{} }
func (m *QueryUTXOsByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUTXOsByAddressResponse) ProtoMessage()    {}
func (*QueryUTXOsByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91cbbf8dfd8cd254, []int{1}
}
func (m *QueryUTXOsByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUTXOsByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUTXOsByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUTXOsByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUTXOsByAddressResponse.Merge(m, src)
}
func (m *QueryUTXOsByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUTXOsByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUTXOsByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUTXOsByAddressResponse proto.InternalMessageInfo

func (m *QueryUTXOsByAddressResponse) GetUtxos() []UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *QueryUTXOsByAddressResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryUTXOsByAddressRequest)(nil), "qbtc.qbtc.v1.QueryUTXOsByAddressRequest")
	proto.RegisterType((*QueryUTXOsByAddressResponse)(nil), "qbtc.qbtc.v1.QueryUTXOsByAddressResponse")
}

func init() { proto.RegisterFile("qbtc/qbtc/v1/query_utxo.proto", fileDescriptor_91cbbf8dfd8cd254) }

var fileDescriptor_91cbbf8dfd8cd254 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0xc7, 0x37, 0xed, 0xf7, 0x89, 0x4d, 0x3d, 0x05, 0x0f, 0xa5, 0xd6, 0x6d, 0x29, 0xa8, 0x8b,
	0x60, 0xc2, 0xd6, 0x07, 0x10, 0x7b, 0xd0, 0xa3, 0xba, 0x28, 0x88, 0x97, 0x92, 0xa4, 0x61, 0x5d,
	0x68, 0x9b, 0xdd, 0x4d, 0xb6, 0xb4, 0x6f, 0xe1, 0xc9, 0x17, 0xf0, 0x65, 0x7a, 0xec, 0xd1, 0x93,
	0x48, 0xf7, 0x45, 0x24, 0x9b, 0x85, 0x6e, 0x41, 0xf0, 0x32, 0x09, 0x33, 0xff, 0x99, 0xff, 0x2f,
	0x19, 0x78, 0x9c, 0x30, 0xcd, 0x49, 0x11, 0xe6, 0x3e, 0x49, 0x32, 0x91, 0x2e, 0x47, 0x99, 0x5e,
	0x48, 0x1c, 0xa7, 0x52, 0x4b, 0x74, 0x60, 0x2a, 0xb8, 0x08, 0x73, 0xbf, 0x7d, 0x18, 0xca, 0x50,
	0x16, 0x05, 0x62, 0x6e, 0x56, 0xd3, 0x3e, 0xe7, 0x52, 0x4d, 0xa5, 0x22, 0x8c, 0x2a, 0x61, 0x27,
	0x90, 0xb9, 0xcf, 0x84, 0xa6, 0x3e, 0x89, 0x69, 0x18, 0xcd, 0xa8, 0x8e, 0xe4, 0xac, 0xd4, 0x76,
	0x76, 0xec, 0xf4, 0x32, 0x16, 0x15, 0xb7, 0xfe, 0x07, 0x80, 0xed, 0x07, 0x33, 0xe0, 0xe9, 0xf1,
	0xf9, 0x4e, 0x0d, 0x97, 0xd7, 0xe3, 0x71, 0x2a, 0x94, 0x0a, 0x44, 0x92, 0x09, 0xa5, 0x51, 0x17,
	0x36, 0x99, 0xe6, 0x23, 0x6a, 0xb3, 0x2d, 0xd0, 0x03, 0x5e, 0x23, 0x80, 0x4c, 0xf3, 0x52, 0x87,
	0x3a, 0xb0, 0xc1, 0x27, 0x34, 0x9a, 0x52, 0x36, 0x11, 0xad, 0x5a, 0x0f, 0x78, 0xfb, 0xc1, 0x36,
	0x81, 0x6e, 0x20, 0xdc, 0xf2, 0xb4, 0xea, 0x3d, 0xe0, 0x35, 0x07, 0xa7, 0xd8, 0xc2, 0x63, 0x03,
	0x8f, 0x0b, 0x78, 0x5c, 0xc2, 0xe3, 0x7b, 0x1a, 0x8a, 0xd2, 0x3a, 0xa8, 0x74, 0xf6, 0xdf, 0x01,
	0x3c, 0xfa, 0x95, 0x52, 0xc5, 0x72, 0xa6, 0x04, 0xc2, 0xf0, 0xbf, 0x79, 0x93, 0x01, 0xac, 0x7b,
	0xcd, 0x01, 0xc2, 0xd5, 0x3f, 0xc4, 0xa6, 0x69, 0xf8, 0x6f, 0xf5, 0xd5, 0x75, 0x02, 0x2b, 0x43,
	0xb7, 0x3b, 0x5c, 0xb5, 0x82, 0xeb, 0xec, 0x4f, 0x2e, 0x6b, 0x56, 0x05, 0x1b, 0x5e, 0xad, 0x36,
	0x2e, 0x58, 0x6f, 0x5c, 0xf0, 0xbd, 0x71, 0xc1, 0x5b, 0xee, 0x3a, 0xeb, 0xdc, 0x75, 0x3e, 0x73,
	0xd7, 0x79, 0x39, 0x09, 0x23, 0xfd, 0x9a, 0x31, 0xcc, 0xe5, 0x94, 0x30, 0xcd, 0x93, 0x0b, 0x99,
	0x86, 0x76, 0x0b, 0x0b, 0x7b, 0x98, 0x4d, 0x28, 0xb6, 0x57, 0xac, 0xe1, 0xf2, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x98, 0x8a, 0x8b, 0x08, 0x15, 0x02, 0x00, 0x00,
}

func (m *QueryUTXOsByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUTXOsByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUTXOsByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryUtxo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Claimable {
		i--
		if m.Claimable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.BtcAddress) > 0 {
		i -= len(m.BtcAddress)
		copy(dAtA[i:], m.BtcAddress)
		i = encodeVarintQueryUtxo(dAtA, i, uint64(len(m.BtcAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUTXOsByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUTXOsByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUTXOsByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryUtxo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Utxos) > 0 {
		for iNdEx := len(m.Utxos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Utxos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryUtxo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryUtxo(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryUtxo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryUTXOsByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BtcAddress)
	if l > 0 {
		n += 1 + l + sovQueryUtxo(uint64(l))
	}
	if m.Claimable {
		n += 2
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQueryUtxo(uint64(l))
	}
	return n
}

func (m *QueryUTXOsByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Utxos) > 0 {
		for _, e := range m.Utxos {
			l = e.Size()
			n += 1 + l + sovQueryUtxo(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQueryUtxo(uint64(l))
	}
	return n
}

func sovQueryUtxo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryUtxo(x uint64) (n int) {
	return sovQueryUtxo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryUTXOsByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryUtxo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUTXOsByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUTXOsByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimable = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryUtxo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUTXOsByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryUtxo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUTXOsByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUTXOsByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utxos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Utxos = append(m.Utxos, UTXO{})
			if err := m.Utxos[len(m.Utxos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryUtxo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryUtxo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryUtxo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryUtxo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryUtxo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryUtxo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryUtxo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryUtxo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryUtxo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryUtxo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryUtxo = fmt.Errorf("proto: unexpected end of group")
)
