// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgEmpty is the return type for all current Msg Server messages
type MsgEmpty struct {
}

func (m *MsgEmpty) Reset()         { *m = MsgEmpty{} }
func (m *MsgEmpty) String() string { return proto.CompactTextString(m) }
func (*MsgEmpty) ProtoMessage()    {}
func (*MsgEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7837ce10d5cd1722, []int{0}
}
func (m *MsgEmpty) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEmpty.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEmpty.Merge(m, src)
}
func (m *MsgEmpty) XXX_Size() int {
	return m.Size()
}
func (m *MsgEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEmpty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgEmpty)(nil), "qbtc.qbtc.v1.MsgEmpty")
}

func init() { proto.RegisterFile("qbtc/qbtc/v1/tx.proto", fileDescriptor_7837ce10d5cd1722) }

var fileDescriptor_7837ce10d5cd1722 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0x13, 0x8a, 0x22, 0x63, 0x40, 0x3a, 0xf8, 0x87, 0x2e, 0xba, 0x88, 0x35, 0x50, 0x44,
	0x77, 0xa9, 0x3e, 0x80, 0x34, 0x25, 0x7a, 0x21, 0xd1, 0xda, 0xb4, 0x20, 0x05, 0x19, 0xf6, 0xcf,
	0x61, 0x5c, 0xda, 0xc9, 0x99, 0xce, 0x9c, 0x84, 0xc4, 0x2b, 0x1f, 0xc1, 0x47, 0xf1, 0x31, 0xbc,
	0xec, 0xa5, 0x97, 0x92, 0x5c, 0xe8, 0x63, 0xc8, 0xce, 0x6c, 0x21, 0x65, 0x5c, 0xbd, 0x99, 0xdd,
	0x39, 0xdf, 0x6f, 0xbf, 0x9d, 0xf3, 0x9d, 0x61, 0x77, 0xce, 0x73, 0x2a, 0x52, 0xb7, 0xcc, 0x76,
	0x53, 0x9a, 0x27, 0xda, 0x20, 0x21, 0xef, 0xd5, 0x95, 0xc4, 0x2d, 0xb3, 0xdd, 0x68, 0x33, 0x53,
	0xd5, 0x04, 0x53, 0xb7, 0x7a, 0x20, 0xba, 0x57, 0xa0, 0x55, 0x68, 0x53, 0x65, 0x65, 0xfd, 0xa1,
	0xb2, 0xb2, 0x11, 0xb6, 0xbc, 0x20, 0xdc, 0x2e, 0xf5, 0x9b, 0x46, 0xba, 0x2d, 0x51, 0xa2, 0xaf,
	0xd7, 0x6f, 0x4d, 0xf5, 0xe9, 0x95, 0x13, 0x28, 0x2b, 0x85, 0x05, 0x12, 0x13, 0x2c, 0x41, 0x68,
	0x00, 0x23, 0xb2, 0xb2, 0x34, 0x60, 0x2f, 0x3d, 0xb6, 0x03, 0xda, 0x80, 0x46, 0x43, 0x22, 0x3f,
	0xc3, 0xe2, 0xb4, 0x81, 0xfa, 0x01, 0x24, 0x71, 0x26, 0x8a, 0xb3, 0xac, 0x52, 0x62, 0x4a, 0x73,
	0x6c, 0xf5, 0x9a, 0xea, 0x32, 0x23, 0x10, 0x3a, 0x33, 0x99, 0x6a, 0xa0, 0xc7, 0x01, 0xe4, 0x7d,
	0xb2, 0xca, 0x94, 0x06, 0x75, 0x43, 0xed, 0x84, 0x4d, 0x4c, 0x73, 0x55, 0x91, 0xf8, 0x7c, 0x2a,
	0x60, 0x42, 0x06, 0xf5, 0xc2, 0x93, 0x8f, 0x18, 0xbb, 0x31, 0xb2, 0x72, 0xa8, 0x34, 0x2d, 0x9e,
	0xff, 0xde, 0x60, 0x1b, 0x23, 0x2b, 0xf9, 0x7b, 0xc6, 0xc7, 0x40, 0x6f, 0xb1, 0x84, 0x03, 0x00,
	0xb3, 0xe7, 0x1b, 0xe6, 0xdb, 0xc9, 0xfa, 0x10, 0x92, 0x91, 0x95, 0x21, 0x14, 0xdd, 0x0d, 0x20,
	0x67, 0xcd, 0x5f, 0xb1, 0xcd, 0x31, 0xd0, 0xc8, 0xca, 0x43, 0x17, 0xcf, 0xa0, 0x4e, 0x87, 0x6f,
	0x05, 0xf0, 0x80, 0x0a, 0x27, 0xb5, 0xfa, 0x0c, 0x59, 0xef, 0x35, 0xce, 0xf6, 0xeb, 0x96, 0x8f,
	0x8f, 0x3e, 0xbc, 0xe3, 0x0f, 0x02, 0x6e, 0x5d, 0x6e, 0xb5, 0xd9, 0x67, 0x37, 0x8f, 0x5d, 0xb6,
	0x07, 0x75, 0xb4, 0xfc, 0x7e, 0x80, 0xad, 0xa9, 0xad, 0x26, 0x47, 0xac, 0xe7, 0xfe, 0xb4, 0xe7,
	0xa3, 0xff, 0xcb, 0x59, 0xd6, 0xe5, 0xa8, 0xff, 0x4f, 0xf9, 0x10, 0xac, 0xc6, 0x89, 0x05, 0xfe,
	0x91, 0xdd, 0x1a, 0xbb, 0x59, 0x9d, 0xbc, 0x19, 0xfa, 0x49, 0xf1, 0x87, 0x61, 0xf2, 0x57, 0x89,
	0x68, 0xe7, 0x7f, 0xc4, 0xa5, 0x7d, 0x74, 0xed, 0xcb, 0xaf, 0x6f, 0x4f, 0xba, 0x83, 0x97, 0xdf,
	0x97, 0x71, 0xf7, 0x62, 0x19, 0x77, 0x7f, 0x2e, 0xe3, 0xee, 0xd7, 0x55, 0xdc, 0xb9, 0x58, 0xc5,
	0x9d, 0x1f, 0xab, 0xb8, 0x73, 0xd2, 0x97, 0x15, 0x7d, 0x9a, 0xe6, 0x49, 0x81, 0x2a, 0xcd, 0xa9,
	0x38, 0x7f, 0x86, 0x46, 0xfa, 0x9b, 0x34, 0xf7, 0x0f, 0x5a, 0x68, 0xb0, 0xf9, 0x75, 0x77, 0x7d,
	0x5e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xc5, 0xd7, 0x43, 0xb1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SetNodePeerAddress allows authorized validators to update their node peer
	// address.
	SetNodePeerAddress(ctx context.Context, in *MsgSetNodePeerAddress, opts ...grpc.CallOption) (*MsgEmpty, error)
	// SetMsgReportBlock is the message for reporting a Bitcoin block.
	SetMsgReportBlock(ctx context.Context, in *MsgBtcBlock, opts ...grpc.CallOption) (*MsgEmpty, error)
	// MsgGovClaimUTXO is the message for claiming a UTXO by the governance
	// module.
	GovClaimUTXO(ctx context.Context, in *MsgGovClaimUTXO, opts ...grpc.CallOption) (*MsgEmpty, error)
	UpdateParam(ctx context.Context, in *MsgUpdateParam, opts ...grpc.CallOption) (*MsgEmpty, error)
	// ClaimAirdrop allows users to claim their airdrop using a ZK proof of Bitcoin address ownership.
	ClaimAirdrop(ctx context.Context, in *MsgClaimAirdrop, opts ...grpc.CallOption) (*MsgClaimAirdropResponse, error)
	// SubmitZKEntropy allows validators to submit entropy for the distributed ZK trusted setup.
	SubmitZKEntropy(ctx context.Context, in *MsgSubmitZKEntropy, opts ...grpc.CallOption) (*MsgSubmitZKEntropyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetNodePeerAddress(ctx context.Context, in *MsgSetNodePeerAddress, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/SetNodePeerAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetMsgReportBlock(ctx context.Context, in *MsgBtcBlock, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/SetMsgReportBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GovClaimUTXO(ctx context.Context, in *MsgGovClaimUTXO, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/GovClaimUTXO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParam(ctx context.Context, in *MsgUpdateParam, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/UpdateParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimAirdrop(ctx context.Context, in *MsgClaimAirdrop, opts ...grpc.CallOption) (*MsgClaimAirdropResponse, error) {
	out := new(MsgClaimAirdropResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/ClaimAirdrop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitZKEntropy(ctx context.Context, in *MsgSubmitZKEntropy, opts ...grpc.CallOption) (*MsgSubmitZKEntropyResponse, error) {
	out := new(MsgSubmitZKEntropyResponse)
	err := c.cc.Invoke(ctx, "/qbtc.qbtc.v1.Msg/SubmitZKEntropy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SetNodePeerAddress allows authorized validators to update their node peer
	// address.
	SetNodePeerAddress(context.Context, *MsgSetNodePeerAddress) (*MsgEmpty, error)
	// SetMsgReportBlock is the message for reporting a Bitcoin block.
	SetMsgReportBlock(context.Context, *MsgBtcBlock) (*MsgEmpty, error)
	// MsgGovClaimUTXO is the message for claiming a UTXO by the governance
	// module.
	GovClaimUTXO(context.Context, *MsgGovClaimUTXO) (*MsgEmpty, error)
	UpdateParam(context.Context, *MsgUpdateParam) (*MsgEmpty, error)
	// ClaimAirdrop allows users to claim their airdrop using a ZK proof of Bitcoin address ownership.
	ClaimAirdrop(context.Context, *MsgClaimAirdrop) (*MsgClaimAirdropResponse, error)
	// SubmitZKEntropy allows validators to submit entropy for the distributed ZK trusted setup.
	SubmitZKEntropy(context.Context, *MsgSubmitZKEntropy) (*MsgSubmitZKEntropyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetNodePeerAddress(ctx context.Context, req *MsgSetNodePeerAddress) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNodePeerAddress not implemented")
}
func (*UnimplementedMsgServer) SetMsgReportBlock(ctx context.Context, req *MsgBtcBlock) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMsgReportBlock not implemented")
}
func (*UnimplementedMsgServer) GovClaimUTXO(ctx context.Context, req *MsgGovClaimUTXO) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GovClaimUTXO not implemented")
}
func (*UnimplementedMsgServer) UpdateParam(ctx context.Context, req *MsgUpdateParam) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParam not implemented")
}
func (*UnimplementedMsgServer) ClaimAirdrop(ctx context.Context, req *MsgClaimAirdrop) (*MsgClaimAirdropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAirdrop not implemented")
}
func (*UnimplementedMsgServer) SubmitZKEntropy(ctx context.Context, req *MsgSubmitZKEntropy) (*MsgSubmitZKEntropyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitZKEntropy not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetNodePeerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetNodePeerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetNodePeerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/SetNodePeerAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetNodePeerAddress(ctx, req.(*MsgSetNodePeerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetMsgReportBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBtcBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetMsgReportBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/SetMsgReportBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetMsgReportBlock(ctx, req.(*MsgBtcBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GovClaimUTXO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGovClaimUTXO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GovClaimUTXO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/GovClaimUTXO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GovClaimUTXO(ctx, req.(*MsgGovClaimUTXO))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/UpdateParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParam(ctx, req.(*MsgUpdateParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimAirdrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimAirdrop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimAirdrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/ClaimAirdrop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimAirdrop(ctx, req.(*MsgClaimAirdrop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitZKEntropy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitZKEntropy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitZKEntropy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qbtc.qbtc.v1.Msg/SubmitZKEntropy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitZKEntropy(ctx, req.(*MsgSubmitZKEntropy))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qbtc.qbtc.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetNodePeerAddress",
			Handler:    _Msg_SetNodePeerAddress_Handler,
		},
		{
			MethodName: "SetMsgReportBlock",
			Handler:    _Msg_SetMsgReportBlock_Handler,
		},
		{
			MethodName: "GovClaimUTXO",
			Handler:    _Msg_GovClaimUTXO_Handler,
		},
		{
			MethodName: "UpdateParam",
			Handler:    _Msg_UpdateParam_Handler,
		},
		{
			MethodName: "ClaimAirdrop",
			Handler:    _Msg_ClaimAirdrop_Handler,
		},
		{
			MethodName: "SubmitZKEntropy",
			Handler:    _Msg_SubmitZKEntropy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qbtc/qbtc/v1/tx.proto",
}

func (m *MsgEmpty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEmpty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEmpty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgEmpty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgEmpty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEmpty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEmpty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
