// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/type_zk_entropy.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ZKEntropySubmission represents a single validator's entropy contribution.
type ZKEntropySubmission struct {
	// The validator address that submitted this entropy
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// The entropy bytes (32 bytes)
	Entropy []byte `protobuf:"bytes,2,opt,name=entropy,proto3" json:"entropy,omitempty"`
	// The block height when this was submitted
	SubmittedAtBlock int64 `protobuf:"varint,3,opt,name=submitted_at_block,json=submittedAtBlock,proto3" json:"submitted_at_block,omitempty"`
	// The commitment hash for verification
	Commitment []byte `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *ZKEntropySubmission) Reset()         { *m = ZKEntropySubmission{} }
func (m *ZKEntropySubmission) String() string { return proto.CompactTextString(m) }
func (*ZKEntropySubmission) ProtoMessage()    {}
func (*ZKEntropySubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34eb49fdb6425ed, []int{0}
}
func (m *ZKEntropySubmission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZKEntropySubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZKEntropySubmission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZKEntropySubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZKEntropySubmission.Merge(m, src)
}
func (m *ZKEntropySubmission) XXX_Size() int {
	return m.Size()
}
func (m *ZKEntropySubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_ZKEntropySubmission.DiscardUnknown(m)
}

var xxx_messageInfo_ZKEntropySubmission proto.InternalMessageInfo

func (m *ZKEntropySubmission) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ZKEntropySubmission) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

func (m *ZKEntropySubmission) GetSubmittedAtBlock() int64 {
	if m != nil {
		return m.SubmittedAtBlock
	}
	return 0
}

func (m *ZKEntropySubmission) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

// ZKEntropyState tracks the state of the distributed entropy collection.
type ZKEntropyState struct {
	// Whether entropy collection is currently active
	CollectionActive bool `protobuf:"varint,1,opt,name=collection_active,json=collectionActive,proto3" json:"collection_active,omitempty"`
	// The block height when collection started
	CollectionStartBlock int64 `protobuf:"varint,2,opt,name=collection_start_block,json=collectionStartBlock,proto3" json:"collection_start_block,omitempty"`
	// All entropy submissions received
	Submissions []ZKEntropySubmission `protobuf:"bytes,3,rep,name=submissions,proto3" json:"submissions"`
	// Whether the setup has been finalized
	SetupFinalized bool `protobuf:"varint,4,opt,name=setup_finalized,json=setupFinalized,proto3" json:"setup_finalized,omitempty"`
	// The combined entropy seed (only set after finalization)
	CombinedSeed []byte `protobuf:"bytes,5,opt,name=combined_seed,json=combinedSeed,proto3" json:"combined_seed,omitempty"`
	// The block height when setup was finalized
	FinalizedAtBlock int64 `protobuf:"varint,6,opt,name=finalized_at_block,json=finalizedAtBlock,proto3" json:"finalized_at_block,omitempty"`
}

func (m *ZKEntropyState) Reset()         { *m = ZKEntropyState{} }
func (m *ZKEntropyState) String() string { return proto.CompactTextString(m) }
func (*ZKEntropyState) ProtoMessage()    {}
func (*ZKEntropyState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34eb49fdb6425ed, []int{1}
}
func (m *ZKEntropyState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZKEntropyState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZKEntropyState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZKEntropyState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZKEntropyState.Merge(m, src)
}
func (m *ZKEntropyState) XXX_Size() int {
	return m.Size()
}
func (m *ZKEntropyState) XXX_DiscardUnknown() {
	xxx_messageInfo_ZKEntropyState.DiscardUnknown(m)
}

var xxx_messageInfo_ZKEntropyState proto.InternalMessageInfo

func (m *ZKEntropyState) GetCollectionActive() bool {
	if m != nil {
		return m.CollectionActive
	}
	return false
}

func (m *ZKEntropyState) GetCollectionStartBlock() int64 {
	if m != nil {
		return m.CollectionStartBlock
	}
	return 0
}

func (m *ZKEntropyState) GetSubmissions() []ZKEntropySubmission {
	if m != nil {
		return m.Submissions
	}
	return nil
}

func (m *ZKEntropyState) GetSetupFinalized() bool {
	if m != nil {
		return m.SetupFinalized
	}
	return false
}

func (m *ZKEntropyState) GetCombinedSeed() []byte {
	if m != nil {
		return m.CombinedSeed
	}
	return nil
}

func (m *ZKEntropyState) GetFinalizedAtBlock() int64 {
	if m != nil {
		return m.FinalizedAtBlock
	}
	return 0
}

// ZKSetupKeys contains the serialized keys from the trusted setup.
// These are stored on-chain after the distributed setup is complete.
type ZKSetupKeys struct {
	// Serialized verifying key (used for on-chain verification)
	VerifyingKey []byte `protobuf:"bytes,1,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"`
	// Hash of the combined entropy seed (for audit purposes)
	SeedHash []byte `protobuf:"bytes,2,opt,name=seed_hash,json=seedHash,proto3" json:"seed_hash,omitempty"`
	// Block height when the keys were generated
	GeneratedAtBlock int64 `protobuf:"varint,3,opt,name=generated_at_block,json=generatedAtBlock,proto3" json:"generated_at_block,omitempty"`
	// List of validators who contributed entropy
	ContributingValidators []string `protobuf:"bytes,4,rep,name=contributing_validators,json=contributingValidators,proto3" json:"contributing_validators,omitempty"`
}

func (m *ZKSetupKeys) Reset()         { *m = ZKSetupKeys{} }
func (m *ZKSetupKeys) String() string { return proto.CompactTextString(m) }
func (*ZKSetupKeys) ProtoMessage()    {}
func (*ZKSetupKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34eb49fdb6425ed, []int{2}
}
func (m *ZKSetupKeys) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZKSetupKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZKSetupKeys.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZKSetupKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZKSetupKeys.Merge(m, src)
}
func (m *ZKSetupKeys) XXX_Size() int {
	return m.Size()
}
func (m *ZKSetupKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ZKSetupKeys.DiscardUnknown(m)
}

var xxx_messageInfo_ZKSetupKeys proto.InternalMessageInfo

func (m *ZKSetupKeys) GetVerifyingKey() []byte {
	if m != nil {
		return m.VerifyingKey
	}
	return nil
}

func (m *ZKSetupKeys) GetSeedHash() []byte {
	if m != nil {
		return m.SeedHash
	}
	return nil
}

func (m *ZKSetupKeys) GetGeneratedAtBlock() int64 {
	if m != nil {
		return m.GeneratedAtBlock
	}
	return 0
}

func (m *ZKSetupKeys) GetContributingValidators() []string {
	if m != nil {
		return m.ContributingValidators
	}
	return nil
}

func init() {
	proto.RegisterType((*ZKEntropySubmission)(nil), "qbtc.qbtc.v1.ZKEntropySubmission")
	proto.RegisterType((*ZKEntropyState)(nil), "qbtc.qbtc.v1.ZKEntropyState")
	proto.RegisterType((*ZKSetupKeys)(nil), "qbtc.qbtc.v1.ZKSetupKeys")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/type_zk_entropy.proto", fileDescriptor_a34eb49fdb6425ed)
}

var fileDescriptor_a34eb49fdb6425ed = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0xb6, 0x8c, 0xd6, 0x2d, 0x63, 0x98, 0x69, 0x44, 0x80, 0x42, 0x29, 0x42, 0x54,
	0x02, 0x5a, 0x0d, 0x90, 0x38, 0xa2, 0x55, 0x02, 0x81, 0x7a, 0x4b, 0x25, 0x0e, 0xbd, 0x44, 0x8e,
	0xf3, 0x2e, 0xb5, 0xda, 0xc4, 0x5d, 0xfc, 0xb6, 0x22, 0xfb, 0x14, 0xdc, 0xf9, 0x1e, 0x1c, 0xf8,
	0x04, 0x3b, 0xee, 0xc8, 0x09, 0xa1, 0xf6, 0x8b, 0x4c, 0x76, 0x9a, 0x3f, 0x87, 0x5d, 0x9c, 0xe4,
	0xf9, 0xd9, 0x7e, 0xde, 0x3c, 0xaf, 0x4d, 0xfa, 0x17, 0x3e, 0xf2, 0x91, 0x19, 0x36, 0xa7, 0x23,
	0x4c, 0x57, 0xe0, 0x5d, 0x2e, 0x3c, 0x88, 0x31, 0x91, 0xab, 0x74, 0xb8, 0x4a, 0x24, 0x4a, 0xda,
	0xd5, 0x78, 0x68, 0x86, 0xcd, 0xe9, 0xe3, 0xe3, 0x50, 0x86, 0xd2, 0x80, 0x91, 0x7e, 0xcb, 0xe6,
	0xf4, 0x7f, 0x59, 0xe4, 0xe1, 0x6c, 0xf2, 0x39, 0x5b, 0x37, 0x5d, 0xfb, 0x91, 0x50, 0x4a, 0xc8,
	0x98, 0x3e, 0x25, 0xed, 0x0d, 0x5b, 0x8a, 0x80, 0xa1, 0x4c, 0x6c, 0xab, 0x67, 0x0d, 0xda, 0x6e,
	0x29, 0x50, 0x9b, 0xdc, 0xdd, 0x5b, 0xd9, 0xf5, 0x9e, 0x35, 0xe8, 0xba, 0xf9, 0x27, 0x7d, 0x43,
	0xa8, 0xd2, 0xbb, 0x20, 0x42, 0xe0, 0x31, 0xf4, 0xfc, 0xa5, 0xe4, 0x0b, 0xbb, 0xd1, 0xb3, 0x06,
	0x0d, 0xf7, 0xa8, 0x20, 0x67, 0x38, 0xd6, 0x3a, 0x75, 0x08, 0xe1, 0x32, 0x8a, 0x04, 0x46, 0x10,
	0xa3, 0xdd, 0x34, 0x5b, 0x55, 0x94, 0xfe, 0x9f, 0x3a, 0x39, 0x2c, 0xab, 0x43, 0x86, 0x40, 0x5f,
	0x93, 0x07, 0x5c, 0x2e, 0x97, 0xc0, 0x51, 0xc8, 0xd8, 0x63, 0x1c, 0xc5, 0x06, 0x4c, 0x81, 0x2d,
	0xf7, 0xa8, 0x04, 0x67, 0x46, 0xa7, 0x1f, 0xc8, 0x49, 0x65, 0xb2, 0x42, 0x96, 0xe4, 0x15, 0xd5,
	0x4d, 0x45, 0xc7, 0x25, 0x9d, 0x6a, 0x98, 0x55, 0xf5, 0x8d, 0x74, 0x54, 0x91, 0x84, 0xb2, 0x1b,
	0xbd, 0xc6, 0xa0, 0xf3, 0xee, 0xf9, 0xb0, 0x9a, 0xe6, 0xf0, 0x96, 0xcc, 0xc6, 0xcd, 0xab, 0x7f,
	0xcf, 0x6a, 0x6e, 0x75, 0x2d, 0x7d, 0x45, 0xee, 0x2b, 0xc0, 0xf5, 0xca, 0x3b, 0x17, 0x31, 0x5b,
	0x8a, 0x4b, 0x08, 0xcc, 0x5f, 0xb6, 0xdc, 0x43, 0x23, 0x7f, 0xc9, 0x55, 0xfa, 0x82, 0xdc, 0xe3,
	0x32, 0xf2, 0x45, 0x0c, 0x81, 0xa7, 0x00, 0x02, 0xfb, 0x8e, 0x09, 0xa3, 0x9b, 0x8b, 0x53, 0x80,
	0x40, 0x87, 0x5b, 0xec, 0x53, 0x86, 0x7b, 0x90, 0x85, 0x5b, 0x90, 0x7d, 0xb8, 0xfd, 0xdf, 0x16,
	0xe9, 0xcc, 0x26, 0x53, 0xed, 0x33, 0x81, 0x54, 0x69, 0x8b, 0x0d, 0x24, 0xe2, 0x3c, 0x15, 0x71,
	0xe8, 0x2d, 0x20, 0x35, 0xa9, 0x75, 0xdd, 0x6e, 0x21, 0x4e, 0x20, 0xa5, 0x4f, 0x48, 0x5b, 0xdb,
	0x7b, 0x73, 0xa6, 0xe6, 0xfb, 0xde, 0xb6, 0xb4, 0xf0, 0x95, 0xa9, 0xb9, 0xf6, 0x0f, 0x21, 0x86,
	0x84, 0xdd, 0xd6, 0xdc, 0x82, 0xe4, 0xcd, 0xfd, 0x48, 0x1e, 0x71, 0x19, 0x63, 0x22, 0xfc, 0x35,
	0x6a, 0xcb, 0xe2, 0xf8, 0x28, 0xbb, 0xd9, 0x6b, 0x0c, 0xda, 0xee, 0x49, 0x15, 0x7f, 0x2f, 0xe8,
	0xf8, 0xd3, 0xd5, 0xd6, 0xb1, 0xae, 0xb7, 0x8e, 0xf5, 0x7f, 0xeb, 0x58, 0x3f, 0x77, 0x4e, 0xed,
	0x7a, 0xe7, 0xd4, 0xfe, 0xee, 0x9c, 0xda, 0xec, 0x65, 0x28, 0x70, 0xbe, 0xf6, 0x87, 0x5c, 0x46,
	0x23, 0x1f, 0xf9, 0xc5, 0x5b, 0x99, 0x84, 0xd9, 0x25, 0xf8, 0x91, 0x3d, 0xf4, 0x45, 0x50, 0xfe,
	0x81, 0x39, 0xdb, 0xef, 0x6f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x9c, 0x9b, 0xb7, 0x25, 0x03,
	0x00, 0x00,
}

func (m *ZKEntropySubmission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZKEntropySubmission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZKEntropySubmission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x22
	}
	if m.SubmittedAtBlock != 0 {
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(m.SubmittedAtBlock))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Entropy) > 0 {
		i -= len(m.Entropy)
		copy(dAtA[i:], m.Entropy)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.Entropy)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ZKEntropyState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZKEntropyState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZKEntropyState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalizedAtBlock != 0 {
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(m.FinalizedAtBlock))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CombinedSeed) > 0 {
		i -= len(m.CombinedSeed)
		copy(dAtA[i:], m.CombinedSeed)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.CombinedSeed)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SetupFinalized {
		i--
		if m.SetupFinalized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Submissions) > 0 {
		for iNdEx := len(m.Submissions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Submissions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypeZkEntropy(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.CollectionStartBlock != 0 {
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(m.CollectionStartBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.CollectionActive {
		i--
		if m.CollectionActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ZKSetupKeys) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZKSetupKeys) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZKSetupKeys) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContributingValidators) > 0 {
		for iNdEx := len(m.ContributingValidators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ContributingValidators[iNdEx])
			copy(dAtA[i:], m.ContributingValidators[iNdEx])
			i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.ContributingValidators[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.GeneratedAtBlock != 0 {
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(m.GeneratedAtBlock))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SeedHash) > 0 {
		i -= len(m.SeedHash)
		copy(dAtA[i:], m.SeedHash)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.SeedHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VerifyingKey) > 0 {
		i -= len(m.VerifyingKey)
		copy(dAtA[i:], m.VerifyingKey)
		i = encodeVarintTypeZkEntropy(dAtA, i, uint64(len(m.VerifyingKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeZkEntropy(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeZkEntropy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ZKEntropySubmission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	l = len(m.Entropy)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	if m.SubmittedAtBlock != 0 {
		n += 1 + sovTypeZkEntropy(uint64(m.SubmittedAtBlock))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	return n
}

func (m *ZKEntropyState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CollectionActive {
		n += 2
	}
	if m.CollectionStartBlock != 0 {
		n += 1 + sovTypeZkEntropy(uint64(m.CollectionStartBlock))
	}
	if len(m.Submissions) > 0 {
		for _, e := range m.Submissions {
			l = e.Size()
			n += 1 + l + sovTypeZkEntropy(uint64(l))
		}
	}
	if m.SetupFinalized {
		n += 2
	}
	l = len(m.CombinedSeed)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	if m.FinalizedAtBlock != 0 {
		n += 1 + sovTypeZkEntropy(uint64(m.FinalizedAtBlock))
	}
	return n
}

func (m *ZKSetupKeys) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VerifyingKey)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	l = len(m.SeedHash)
	if l > 0 {
		n += 1 + l + sovTypeZkEntropy(uint64(l))
	}
	if m.GeneratedAtBlock != 0 {
		n += 1 + sovTypeZkEntropy(uint64(m.GeneratedAtBlock))
	}
	if len(m.ContributingValidators) > 0 {
		for _, s := range m.ContributingValidators {
			l = len(s)
			n += 1 + l + sovTypeZkEntropy(uint64(l))
		}
	}
	return n
}

func sovTypeZkEntropy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeZkEntropy(x uint64) (n int) {
	return sovTypeZkEntropy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ZKEntropySubmission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeZkEntropy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZKEntropySubmission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZKEntropySubmission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entropy", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entropy = append(m.Entropy[:0], dAtA[iNdEx:postIndex]...)
			if m.Entropy == nil {
				m.Entropy = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedAtBlock", wireType)
			}
			m.SubmittedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmittedAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeZkEntropy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ZKEntropyState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeZkEntropy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZKEntropyState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZKEntropyState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CollectionActive = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionStartBlock", wireType)
			}
			m.CollectionStartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionStartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submissions = append(m.Submissions, ZKEntropySubmission{})
			if err := m.Submissions[len(m.Submissions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetupFinalized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetupFinalized = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CombinedSeed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CombinedSeed = append(m.CombinedSeed[:0], dAtA[iNdEx:postIndex]...)
			if m.CombinedSeed == nil {
				m.CombinedSeed = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedAtBlock", wireType)
			}
			m.FinalizedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypeZkEntropy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ZKSetupKeys) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeZkEntropy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZKSetupKeys: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZKSetupKeys: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyingKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifyingKey = append(m.VerifyingKey[:0], dAtA[iNdEx:postIndex]...)
			if m.VerifyingKey == nil {
				m.VerifyingKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeedHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SeedHash = append(m.SeedHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SeedHash == nil {
				m.SeedHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GeneratedAtBlock", wireType)
			}
			m.GeneratedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GeneratedAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributingValidators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributingValidators = append(m.ContributingValidators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeZkEntropy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeZkEntropy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeZkEntropy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeZkEntropy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeZkEntropy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeZkEntropy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeZkEntropy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeZkEntropy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeZkEntropy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeZkEntropy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeZkEntropy = fmt.Errorf("proto: unexpected end of group")
)
