// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/type_btc_vote_ext.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BtcBlockVoteExtension is attached by each validator to its CometBFT precommit
// via ABCI 2.0 ExtendVote. It carries only digests of the Bitcoin blocks the
// validator has observed and is ready to attest to — never the block contents
// themselves, which would bloat every precommit.
type BtcBlockVoteExtension struct {
	Items []*BtcBlockAttest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (m *BtcBlockVoteExtension) Reset()         { *m = BtcBlockVoteExtension{} }
func (m *BtcBlockVoteExtension) String() string { return proto.CompactTextString(m) }
func (*BtcBlockVoteExtension) ProtoMessage()    {}
func (*BtcBlockVoteExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_a328b2d4ab748243, []int{0}
}
func (m *BtcBlockVoteExtension) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BtcBlockVoteExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BtcBlockVoteExtension.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BtcBlockVoteExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BtcBlockVoteExtension.Merge(m, src)
}
func (m *BtcBlockVoteExtension) XXX_Size() int {
	return m.Size()
}
func (m *BtcBlockVoteExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_BtcBlockVoteExtension.DiscardUnknown(m)
}

var xxx_messageInfo_BtcBlockVoteExtension proto.InternalMessageInfo

// BtcBlockAttest is one validator's attestation digest for a single Bitcoin
// block height.
type BtcBlockAttest struct {
	// The Bitcoin block height being attested.
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// The Bitcoin block hash (display order).
	BlockHash []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// sha256 of the canonical BtcBlockDelta bytes for this height. The precommit
	// signature over the vote extension (produced by CometBFT) is what binds this
	// digest to the validator's voting power.
	DeltaHash []byte `protobuf:"bytes,3,opt,name=delta_hash,json=deltaHash,proto3" json:"delta_hash,omitempty"`
}

func (m *BtcBlockAttest) Reset()         { *m = BtcBlockAttest{} }
func (m *BtcBlockAttest) String() string { return proto.CompactTextString(m) }
func (*BtcBlockAttest) ProtoMessage()    {}
func (*BtcBlockAttest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a328b2d4ab748243, []int{1}
}
func (m *BtcBlockAttest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BtcBlockAttest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BtcBlockAttest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BtcBlockAttest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BtcBlockAttest.Merge(m, src)
}
func (m *BtcBlockAttest) XXX_Size() int {
	return m.Size()
}
func (m *BtcBlockAttest) XXX_DiscardUnknown() {
	xxx_messageInfo_BtcBlockAttest.DiscardUnknown(m)
}

var xxx_messageInfo_BtcBlockAttest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BtcBlockVoteExtension)(nil), "qbtc.qbtc.v1.BtcBlockVoteExtension")
	proto.RegisterType((*BtcBlockAttest)(nil), "qbtc.qbtc.v1.BtcBlockAttest")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/type_btc_vote_ext.proto", fileDescriptor_a328b2d4ab748243)
}

var fileDescriptor_a328b2d4ab748243 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4c, 0x2a, 0x49,
	0xd6, 0x07, 0x13, 0x65, 0x86, 0xfa, 0x25, 0x95, 0x05, 0xa9, 0xf1, 0x49, 0x25, 0xc9, 0xf1, 0x65,
	0xf9, 0x25, 0xa9, 0xf1, 0xa9, 0x15, 0x25, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x20,
	0x05, 0x7a, 0x60, 0xa2, 0xcc, 0x50, 0x4a, 0x24, 0x3d, 0x3f, 0x3d, 0x1f, 0x2c, 0xa1, 0x0f, 0x62,
	0x41, 0xd4, 0x28, 0x79, 0x73, 0x89, 0x3a, 0x95, 0x24, 0x3b, 0xe5, 0xe4, 0x27, 0x67, 0x87, 0xe5,
	0x97, 0xa4, 0xba, 0x56, 0x94, 0xa4, 0xe6, 0x15, 0x67, 0xe6, 0xe7, 0x09, 0x19, 0x71, 0xb1, 0x66,
	0x96, 0xa4, 0xe6, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xc9, 0xe8, 0x21, 0x1b, 0xa6,
	0x07, 0xd3, 0xe3, 0x58, 0x52, 0x92, 0x5a, 0x5c, 0x12, 0x04, 0x51, 0xaa, 0x94, 0xc6, 0xc5, 0x87,
	0x2a, 0x21, 0x24, 0xc6, 0xc5, 0x96, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x12, 0x04, 0xe5, 0x09, 0xc9, 0x72, 0x71, 0x25, 0x81, 0x94, 0xc5, 0x67, 0x24, 0x16, 0x67,
	0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x71, 0x82, 0x45, 0x3c, 0x12, 0x8b, 0x33, 0x40, 0xd2,
	0x29, 0xa9, 0x39, 0x25, 0x89, 0x10, 0x69, 0x66, 0x88, 0x34, 0x58, 0x04, 0x24, 0xed, 0xe4, 0x7c,
	0xe2, 0xa1, 0x1c, 0xc3, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7,
	0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xa9, 0xa6,
	0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x27, 0x95, 0x24, 0x17, 0xea, 0xe6,
	0x17, 0xa5, 0x43, 0xc2, 0xaa, 0x02, 0x42, 0x81, 0xc2, 0xab, 0x38, 0x89, 0x0d, 0x1c, 0x00, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x58, 0xae, 0x7f, 0x4c, 0x01, 0x00, 0x00,
}

func (m *BtcBlockVoteExtension) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BtcBlockVoteExtension) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BtcBlockVoteExtension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypeBtcVoteExt(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BtcBlockAttest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BtcBlockAttest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BtcBlockAttest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeltaHash) > 0 {
		i -= len(m.DeltaHash)
		copy(dAtA[i:], m.DeltaHash)
		i = encodeVarintTypeBtcVoteExt(dAtA, i, uint64(len(m.DeltaHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintTypeBtcVoteExt(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTypeBtcVoteExt(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeBtcVoteExt(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeBtcVoteExt(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BtcBlockVoteExtension) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTypeBtcVoteExt(uint64(l))
		}
	}
	return n
}

func (m *BtcBlockAttest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTypeBtcVoteExt(uint64(m.Height))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovTypeBtcVoteExt(uint64(l))
	}
	l = len(m.DeltaHash)
	if l > 0 {
		n += 1 + l + sovTypeBtcVoteExt(uint64(l))
	}
	return n
}

func sovTypeBtcVoteExt(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeBtcVoteExt(x uint64) (n int) {
	return sovTypeBtcVoteExt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BtcBlockVoteExtension) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeBtcVoteExt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BtcBlockVoteExtension: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BtcBlockVoteExtension: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &BtcBlockAttest{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeBtcVoteExt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BtcBlockAttest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeBtcVoteExt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BtcBlockAttest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BtcBlockAttest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeltaHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeltaHash = append(m.DeltaHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DeltaHash == nil {
				m.DeltaHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeBtcVoteExt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeBtcVoteExt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeBtcVoteExt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeBtcVoteExt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeBtcVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeBtcVoteExt
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeBtcVoteExt
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeBtcVoteExt
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeBtcVoteExt        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeBtcVoteExt          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeBtcVoteExt = fmt.Errorf("proto: unexpected end of group")
)
