// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/qbtc/v1/type_block_gossip.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BlockGossip represents a gossiped Bitcoin block along with an attestation.
type BlockGossip struct {
	// The height of the Bitcoin block being gossiped.
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// The 32-byte hash of the Bitcoin block being gossiped.
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// The structured block commit (header + slim transactions). The attached
	// attestation is a signature over proto.Marshal(commit).
	Commit *BtcBlockCommit `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	// An attestation for the gossiped block.
	Attestation *Attestation `protobuf:"bytes,4,opt,name=attestation,proto3" json:"attestation,omitempty"`
}

func (m *BlockGossip) Reset()         { *m = BlockGossip{} }
func (m *BlockGossip) String() string { return proto.CompactTextString(m) }
func (*BlockGossip) ProtoMessage()    {}
func (*BlockGossip) Descriptor() ([]byte, []int) {
	return fileDescriptor_60f045a3ef7d8fd3, []int{0}
}
func (m *BlockGossip) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockGossip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockGossip.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockGossip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockGossip.Merge(m, src)
}
func (m *BlockGossip) XXX_Size() int {
	return m.Size()
}
func (m *BlockGossip) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockGossip.DiscardUnknown(m)
}

var xxx_messageInfo_BlockGossip proto.InternalMessageInfo

func (m *BlockGossip) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockGossip) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockGossip) GetCommit() *BtcBlockCommit {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *BlockGossip) GetAttestation() *Attestation {
	if m != nil {
		return m.Attestation
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockGossip)(nil), "qbtc.qbtc.v1.BlockGossip")
}

func init() {
	proto.RegisterFile("qbtc/qbtc/v1/type_block_gossip.proto", fileDescriptor_60f045a3ef7d8fd3)
}

var fileDescriptor_60f045a3ef7d8fd3 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4c, 0x2a, 0x49,
	0xd6, 0x07, 0x13, 0x65, 0x86, 0xfa, 0x25, 0x95, 0x05, 0xa9, 0xf1, 0x49, 0x39, 0xf9, 0xc9, 0xd9,
	0xf1, 0xe9, 0xf9, 0xc5, 0xc5, 0x99, 0x05, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x20,
	0x05, 0x7a, 0x60, 0xa2, 0xcc, 0x50, 0x4a, 0x19, 0x45, 0x4f, 0x6e, 0x71, 0x7a, 0x7c, 0x51, 0x6a,
	0x41, 0x7e, 0x51, 0x09, 0x44, 0x27, 0x44, 0x8b, 0xd2, 0x1a, 0x46, 0x2e, 0x6e, 0x27, 0x10, 0xdf,
	0x1d, 0x6c, 0x90, 0x90, 0x18, 0x17, 0x5b, 0x46, 0x6a, 0x66, 0x7a, 0x46, 0x89, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x4b, 0x10, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xa4,
	0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x0b, 0x99, 0x70, 0xb1, 0x25, 0xe7, 0xe7, 0xe6, 0x66, 0x96,
	0x48, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x1b, 0xc9, 0xe8, 0x21, 0xdb, 0xaf, 0xe7, 0x54, 0x92, 0x0c,
	0x36, 0xd9, 0x19, 0xac, 0x26, 0x08, 0xaa, 0x56, 0xc8, 0x9a, 0x8b, 0x3b, 0xb1, 0xa4, 0x24, 0xb5,
	0xb8, 0x24, 0xb1, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x05, 0xac, 0x55, 0x12, 0x55, 0xab, 0x23, 0x42,
	0x41, 0x10, 0xb2, 0x6a, 0x27, 0xfb, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0,
	0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88,
	0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2a, 0x49, 0x2e,
	0xd4, 0xcd, 0x2f, 0x4a, 0x87, 0x78, 0xbe, 0x02, 0x42, 0x81, 0x02, 0xad, 0x38, 0x89, 0x0d, 0xec,
	0x6d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xcd, 0x22, 0x17, 0x51, 0x01, 0x00, 0x00,
}

func (m *BlockGossip) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockGossip) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockGossip) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Attestation != nil {
		{
			size, err := m.Attestation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypeBlockGossip(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Commit != nil {
		{
			size, err := m.Commit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypeBlockGossip(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintTypeBlockGossip(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTypeBlockGossip(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeBlockGossip(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeBlockGossip(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BlockGossip) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTypeBlockGossip(uint64(m.Height))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovTypeBlockGossip(uint64(l))
	}
	if m.Commit != nil {
		l = m.Commit.Size()
		n += 1 + l + sovTypeBlockGossip(uint64(l))
	}
	if m.Attestation != nil {
		l = m.Attestation.Size()
		n += 1 + l + sovTypeBlockGossip(uint64(l))
	}
	return n
}

func sovTypeBlockGossip(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeBlockGossip(x uint64) (n int) {
	return sovTypeBlockGossip(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BlockGossip) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeBlockGossip
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockGossip: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockGossip: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Commit == nil {
				m.Commit = &BtcBlockCommit{}
			}
			if err := m.Commit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Attestation == nil {
				m.Attestation = &Attestation{}
			}
			if err := m.Attestation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeBlockGossip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeBlockGossip
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeBlockGossip(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeBlockGossip
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeBlockGossip
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeBlockGossip
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeBlockGossip
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeBlockGossip
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeBlockGossip        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeBlockGossip          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeBlockGossip = fmt.Errorf("proto: unexpected end of group")
)
