FROM alpine:3.23

WORKDIR /qbtc_data
ENV HOME=/qbtc_data
COPY qbtcd /usr/bin/qbtcd
COPY bifrost /usr/bin/bifrost
RUN apk add -U --no-cache ca-certificates

CMD ["qbtcd", "start", "--home", "/qbtc_data/.qbtc"]
