// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: btcq/btcq/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("btcq/btcq/v1/query.proto", fileDescriptor_e46a10e1e5087035) }

var fileDescriptor_e46a10e1e5087035 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xb7, 0xe2, 0x7a, 0xa8, 0x7a, 0x30, 0x2e, 0x22, 0xcb, 0x1a, 0x45, 0xf0, 0x22, 0xd8,
	0x50, 0x7d, 0x00, 0xc1, 0x07, 0x10, 0xf4, 0xe8, 0x65, 0x49, 0xb7, 0x43, 0x2c, 0xb8, 0x99, 0xb6,
	0x93, 0x16, 0x17, 0xf1, 0xe2, 0x13, 0x08, 0xbe, 0x94, 0x37, 0x17, 0xbc, 0x78, 0x94, 0xd6, 0x07,
	0x91, 0x24, 0x15, 0x05, 0xe9, 0x65, 0x3a, 0xfc, 0x3f, 0xfa, 0x1b, 0x12, 0xee, 0x26, 0x66, 0x56,
	0x08, 0x37, 0xea, 0x58, 0x14, 0x15, 0x94, 0x8b, 0x28, 0x2f, 0xd1, 0x20, 0xdb, 0xb0, 0x62, 0xe4,
	0x46, 0x1d, 0x8f, 0xb7, 0xe4, 0x3c, 0xd3, 0x28, 0xdc, 0xf4, 0x81, 0xf1, 0xf1, 0x0c, 0x69, 0x8e,
	0x24, 0x12, 0x49, 0xe0, 0x9b, 0xa2, 0x8e, 0x13, 0x30, 0x32, 0x16, 0xb9, 0x54, 0x99, 0x96, 0x26,
	0x43, 0xdd, 0x65, 0x47, 0x0a, 0x15, 0xba, 0x55, 0xd8, 0xad, 0x53, 0x27, 0x0a, 0x51, 0xdd, 0x81,
	0x90, 0x79, 0x26, 0xa4, 0xd6, 0x68, 0x5c, 0x85, 0x3a, 0x77, 0xef, 0xff, 0x69, 0x53, 0x8d, 0x29,
	0x78, 0xfb, 0xf4, 0x2d, 0x08, 0x87, 0x57, 0x56, 0x64, 0x10, 0xae, 0x5e, 0x62, 0x0a, 0x8c, 0x47,
	0x7f, 0x4f, 0x8e, 0x9c, 0x69, 0x8d, 0x6b, 0x28, 0x2a, 0x20, 0x33, 0xde, 0xef, 0xf5, 0x29, 0x47,
	0x4d, 0x70, 0x38, 0x79, 0x7a, 0xff, 0x7a, 0x59, 0xd9, 0x61, 0x23, 0x4f, 0xb5, 0x30, 0xf1, 0x20,
	0xd3, 0xb4, 0x04, 0xa2, 0x47, 0x36, 0x0d, 0x87, 0x36, 0x4d, 0xac, 0xef, 0x3f, 0xf4, 0x03, 0x3a,
	0xe8, 0x0f, 0x74, 0xa4, 0x6d, 0x47, 0xda, 0x64, 0xeb, 0xbf, 0x24, 0xba, 0x38, 0x7f, 0x6d, 0x78,
	0xb0, 0x6c, 0x78, 0xf0, 0xd9, 0xf0, 0xe0, 0xb9, 0xe5, 0x83, 0x65, 0xcb, 0x07, 0x1f, 0x2d, 0x1f,
	0xdc, 0x1c, 0xa9, 0xcc, 0xdc, 0x56, 0x49, 0x34, 0xc3, 0xb9, 0x2b, 0x9c, 0x60, 0xa9, 0x7c, 0xf3,
	0xde, 0x7f, 0xcc, 0x22, 0x07, 0x4a, 0xd6, 0xdc, 0xcb, 0x9c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0xcd, 0xab, 0x1e, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Node(ctx context.Context, in *QueryNodeRequest, opts ...grpc.CallOption) (*QueryNodeResponse, error)
	Nodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Node(ctx context.Context, in *QueryNodeRequest, opts ...grpc.CallOption) (*QueryNodeResponse, error) {
	out := new(QueryNodeResponse)
	err := c.cc.Invoke(ctx, "/btcq.btcq.v1.Query/Node", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Nodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error) {
	out := new(QueryNodesResponse)
	err := c.cc.Invoke(ctx, "/btcq.btcq.v1.Query/Nodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Node(context.Context, *QueryNodeRequest) (*QueryNodeResponse, error)
	Nodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Node(ctx context.Context, req *QueryNodeRequest) (*QueryNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Node not implemented")
}
func (*UnimplementedQueryServer) Nodes(ctx context.Context, req *QueryNodesRequest) (*QueryNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nodes not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Node_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Node(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/btcq.btcq.v1.Query/Node",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Node(ctx, req.(*QueryNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Nodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/btcq.btcq.v1.Query/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Nodes(ctx, req.(*QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "btcq.btcq.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Node",
			Handler:    _Query_Node_Handler,
		},
		{
			MethodName: "Nodes",
			Handler:    _Query_Nodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "btcq/btcq/v1/query.proto",
}
