// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/lp/v1/msg_withdraw_liquidity.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgWithdrawLiquidity withdraws a basis-points fraction of an LP's free
// (non-bonded) units. The qbtc side pays out on-chain; the BTC side is
// enqueued as a TxOutItem in the secured module to the LP's already-proven
// btc_address. Bonded units must be released via MsgUnbond first.
type MsgWithdrawLiquidity struct {
	Signer      string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	NodeId      string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BasisPoints uint32 `protobuf:"varint,3,opt,name=basis_points,json=basisPoints,proto3" json:"basis_points,omitempty"`
}

func (m *MsgWithdrawLiquidity) Reset()         { *m = MsgWithdrawLiquidity{} }
func (m *MsgWithdrawLiquidity) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawLiquidity) ProtoMessage()    {}
func (*MsgWithdrawLiquidity) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b98a713f27693f2, []int{0}
}
func (m *MsgWithdrawLiquidity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawLiquidity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawLiquidity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawLiquidity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawLiquidity.Merge(m, src)
}
func (m *MsgWithdrawLiquidity) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawLiquidity) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawLiquidity.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawLiquidity proto.InternalMessageInfo

func (m *MsgWithdrawLiquidity) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgWithdrawLiquidity) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MsgWithdrawLiquidity) GetBasisPoints() uint32 {
	if m != nil {
		return m.BasisPoints
	}
	return 0
}

type MsgWithdrawLiquidityResponse struct {
	QbtcOut string `protobuf:"bytes,1,opt,name=qbtc_out,json=qbtcOut,proto3" json:"qbtc_out,omitempty"`
	SbtcOut string `protobuf:"bytes,2,opt,name=sbtc_out,json=sbtcOut,proto3" json:"sbtc_out,omitempty"`
	TxOutId uint64 `protobuf:"varint,3,opt,name=tx_out_id,json=txOutId,proto3" json:"tx_out_id,omitempty"`
}

func (m *MsgWithdrawLiquidityResponse) Reset()         { *m = MsgWithdrawLiquidityResponse{} }
func (m *MsgWithdrawLiquidityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawLiquidityResponse) ProtoMessage()    {}
func (*MsgWithdrawLiquidityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b98a713f27693f2, []int{1}
}
func (m *MsgWithdrawLiquidityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawLiquidityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawLiquidityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawLiquidityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawLiquidityResponse.Merge(m, src)
}
func (m *MsgWithdrawLiquidityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawLiquidityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawLiquidityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawLiquidityResponse proto.InternalMessageInfo

func (m *MsgWithdrawLiquidityResponse) GetQbtcOut() string {
	if m != nil {
		return m.QbtcOut
	}
	return ""
}

func (m *MsgWithdrawLiquidityResponse) GetSbtcOut() string {
	if m != nil {
		return m.SbtcOut
	}
	return ""
}

func (m *MsgWithdrawLiquidityResponse) GetTxOutId() uint64 {
	if m != nil {
		return m.TxOutId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgWithdrawLiquidity)(nil), "qbtc.lp.v1.MsgWithdrawLiquidity")
	proto.RegisterType((*MsgWithdrawLiquidityResponse)(nil), "qbtc.lp.v1.MsgWithdrawLiquidityResponse")
}

func init() {
	proto.RegisterFile("qbtc/lp/v1/msg_withdraw_liquidity.proto", fileDescriptor_1b98a713f27693f2)
}

var fileDescriptor_1b98a713f27693f2 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0x8d, 0xef, 0x8b, 0xbe, 0xee, 0xdb, 0x1e, 0x1a, 0x04, 0xa3, 0x94, 0x60, 0xed, 0x41,
	0x11, 0xcc, 0x56, 0x7a, 0x2b, 0xf4, 0x50, 0x6f, 0x42, 0x8b, 0x25, 0x3d, 0x14, 0x7a, 0x09, 0x26,
	0x1b, 0xe2, 0x42, 0x92, 0x5d, 0x33, 0x1b, 0xff, 0x5c, 0x7b, 0xec, 0xa9, 0x1f, 0xc5, 0x43, 0xbf,
	0x43, 0x7b, 0x94, 0x9e, 0x7a, 0x2c, 0x7a, 0xf0, 0x6b, 0x94, 0x4d, 0xd6, 0x9b, 0xd0, 0xcb, 0xc2,
	0xcc, 0x6f, 0x66, 0x9e, 0x99, 0x7d, 0x50, 0x7b, 0xea, 0x0a, 0x0f, 0x87, 0x1c, 0xcf, 0xfa, 0x38,
	0x82, 0xc0, 0x99, 0x53, 0x31, 0x21, 0xc9, 0x78, 0xee, 0x84, 0x74, 0x9a, 0x52, 0x42, 0xc5, 0xd2,
	0xe2, 0x09, 0x13, 0x4c, 0x47, 0xb2, 0xd0, 0x0a, 0xb9, 0x35, 0xeb, 0x37, 0x4e, 0xc6, 0x11, 0x8d,
	0x19, 0xce, 0xde, 0x1c, 0x37, 0x6a, 0x1e, 0x83, 0x88, 0x81, 0x9c, 0xa1, 0x46, 0x29, 0x50, 0xcf,
	0x81, 0x93, 0x45, 0x38, 0x0f, 0x72, 0xd4, 0x7a, 0xd7, 0x50, 0xf5, 0x0e, 0x82, 0x47, 0x25, 0x79,
	0xbb, 0x57, 0xd4, 0x2f, 0x50, 0x09, 0x68, 0x10, 0xfb, 0x89, 0xa1, 0x35, 0xb5, 0x4e, 0x65, 0x60,
	0x7c, 0xbe, 0xf5, 0xaa, 0xaa, 0xf5, 0x86, 0x90, 0xc4, 0x07, 0x78, 0x10, 0x09, 0x8d, 0x03, 0x5b,
	0xd5, 0xe9, 0x7d, 0x54, 0x8e, 0x19, 0xf1, 0x1d, 0x4a, 0x8c, 0xe2, 0x6f, 0x2d, 0xb2, 0x70, 0x48,
	0xf4, 0x33, 0x74, 0xe4, 0x8e, 0x81, 0x82, 0xc3, 0x19, 0x8d, 0x05, 0x18, 0x7f, 0x9a, 0x5a, 0xe7,
	0xd8, 0xfe, 0x9f, 0xe5, 0xee, 0xb3, 0xd4, 0x55, 0xfb, 0x79, 0xb7, 0xea, 0x2a, 0x89, 0x97, 0xdd,
	0xaa, 0x5b, 0x0b, 0x39, 0x3e, 0xb4, 0x70, 0x8b, 0xa3, 0xd3, 0x43, 0x79, 0xdb, 0x07, 0xce, 0x62,
	0xf0, 0xf5, 0x3a, 0xfa, 0x27, 0xbf, 0xcf, 0x61, 0xa9, 0xc8, 0x4f, 0xb2, 0xcb, 0x32, 0x1e, 0xa5,
	0x42, 0x22, 0xd8, 0xa3, 0x62, 0x8e, 0x40, 0xa1, 0x06, 0xaa, 0x88, 0x85, 0x04, 0xf2, 0x2c, 0xb9,
	0xde, 0x5f, 0xbb, 0x2c, 0x16, 0xa3, 0x54, 0x0c, 0xc9, 0xe0, 0xfa, 0x63, 0x63, 0x6a, 0xeb, 0x8d,
	0xa9, 0x7d, 0x6f, 0x4c, 0xed, 0x75, 0x6b, 0x16, 0xd6, 0x5b, 0xb3, 0xf0, 0xb5, 0x35, 0x0b, 0x4f,
	0xe7, 0x01, 0x15, 0x93, 0xd4, 0xb5, 0x3c, 0x16, 0x61, 0x57, 0x78, 0xd3, 0x1e, 0x4b, 0x02, 0x9c,
	0xb9, 0xbc, 0x90, 0x3e, 0x8b, 0x25, 0xf7, 0xc1, 0x2d, 0x65, 0x0e, 0x5c, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x2f, 0x82, 0x46, 0x0e, 0xff, 0x01, 0x00, 0x00,
}

func (m *MsgWithdrawLiquidity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawLiquidity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawLiquidity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BasisPoints != 0 {
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(m.BasisPoints))
		i--
		dAtA[i] = 0x18
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawLiquidityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawLiquidityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawLiquidityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxOutId != 0 {
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(m.TxOutId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SbtcOut) > 0 {
		i -= len(m.SbtcOut)
		copy(dAtA[i:], m.SbtcOut)
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(len(m.SbtcOut)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.QbtcOut) > 0 {
		i -= len(m.QbtcOut)
		copy(dAtA[i:], m.QbtcOut)
		i = encodeVarintMsgWithdrawLiquidity(dAtA, i, uint64(len(m.QbtcOut)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgWithdrawLiquidity(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgWithdrawLiquidity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWithdrawLiquidity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgWithdrawLiquidity(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovMsgWithdrawLiquidity(uint64(l))
	}
	if m.BasisPoints != 0 {
		n += 1 + sovMsgWithdrawLiquidity(uint64(m.BasisPoints))
	}
	return n
}

func (m *MsgWithdrawLiquidityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QbtcOut)
	if l > 0 {
		n += 1 + l + sovMsgWithdrawLiquidity(uint64(l))
	}
	l = len(m.SbtcOut)
	if l > 0 {
		n += 1 + l + sovMsgWithdrawLiquidity(uint64(l))
	}
	if m.TxOutId != 0 {
		n += 1 + sovMsgWithdrawLiquidity(uint64(m.TxOutId))
	}
	return n
}

func sovMsgWithdrawLiquidity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgWithdrawLiquidity(x uint64) (n int) {
	return sovMsgWithdrawLiquidity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgWithdrawLiquidity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithdrawLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawLiquidity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawLiquidity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasisPoints", wireType)
			}
			m.BasisPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BasisPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithdrawLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawLiquidityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgWithdrawLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawLiquidityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawLiquidityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QbtcOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QbtcOut = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SbtcOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SbtcOut = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOutId", wireType)
			}
			m.TxOutId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxOutId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgWithdrawLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgWithdrawLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgWithdrawLiquidity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgWithdrawLiquidity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgWithdrawLiquidity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgWithdrawLiquidity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgWithdrawLiquidity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgWithdrawLiquidity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgWithdrawLiquidity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgWithdrawLiquidity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgWithdrawLiquidity = fmt.Errorf("proto: unexpected end of group")
)
