// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/lp/v1/msg_swap.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSwap performs one of three on-chain swap pairs. The fourth pair (BTC L1
// -> qbtc) is memo-driven and observed via x/secured.MsgObservedTxIn rather
// than a user-signed MsgSwap.
//
//	source_denom -> dest_denom legal pairs:
//	  qbtc -> sbtc   (purely on-chain)
//	  qbtc -> btc    (queues a vault outbound; dest_address is BTC bech32)
//	  sbtc -> qbtc   (purely on-chain)
//
// No affiliate fields.
type MsgSwap struct {
	Signer      string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	SourceDenom string                 `protobuf:"bytes,2,opt,name=source_denom,json=sourceDenom,proto3" json:"source_denom,omitempty"`
	Amount      cosmossdk_io_math.Uint `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Uint" json:"amount"`
	MinOut      cosmossdk_io_math.Uint `protobuf:"bytes,4,opt,name=min_out,json=minOut,proto3,customtype=cosmossdk.io/math.Uint" json:"min_out"`
	DestDenom   string                 `protobuf:"bytes,5,opt,name=dest_denom,json=destDenom,proto3" json:"dest_denom,omitempty"`
	DestAddress string                 `protobuf:"bytes,6,opt,name=dest_address,json=destAddress,proto3" json:"dest_address,omitempty"`
}

func (m *MsgSwap) Reset()         { *m = MsgSwap{} }
func (m *MsgSwap) String() string { return proto.CompactTextString(m) }
func (*MsgSwap) ProtoMessage()    {}
func (*MsgSwap) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fbfc3957073c305, []int{0}
}
func (m *MsgSwap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwap.Merge(m, src)
}
func (m *MsgSwap) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwap) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwap.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwap proto.InternalMessageInfo

func (m *MsgSwap) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSwap) GetSourceDenom() string {
	if m != nil {
		return m.SourceDenom
	}
	return ""
}

func (m *MsgSwap) GetDestDenom() string {
	if m != nil {
		return m.DestDenom
	}
	return ""
}

func (m *MsgSwap) GetDestAddress() string {
	if m != nil {
		return m.DestAddress
	}
	return ""
}

type MsgSwapResponse struct {
	OutAmount string `protobuf:"bytes,1,opt,name=out_amount,json=outAmount,proto3" json:"out_amount,omitempty"`
	SlipBps   uint32 `protobuf:"varint,2,opt,name=slip_bps,json=slipBps,proto3" json:"slip_bps,omitempty"`
	TxOutId   uint64 `protobuf:"varint,3,opt,name=tx_out_id,json=txOutId,proto3" json:"tx_out_id,omitempty"`
}

func (m *MsgSwapResponse) Reset()         { *m = MsgSwapResponse{} }
func (m *MsgSwapResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSwapResponse) ProtoMessage()    {}
func (*MsgSwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fbfc3957073c305, []int{1}
}
func (m *MsgSwapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwapResponse.Merge(m, src)
}
func (m *MsgSwapResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwapResponse proto.InternalMessageInfo

func (m *MsgSwapResponse) GetOutAmount() string {
	if m != nil {
		return m.OutAmount
	}
	return ""
}

func (m *MsgSwapResponse) GetSlipBps() uint32 {
	if m != nil {
		return m.SlipBps
	}
	return 0
}

func (m *MsgSwapResponse) GetTxOutId() uint64 {
	if m != nil {
		return m.TxOutId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSwap)(nil), "qbtc.lp.v1.MsgSwap")
	proto.RegisterType((*MsgSwapResponse)(nil), "qbtc.lp.v1.MsgSwapResponse")
}

func init() { proto.RegisterFile("qbtc/lp/v1/msg_swap.proto", fileDescriptor_3fbfc3957073c305) }

var fileDescriptor_3fbfc3957073c305 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6b, 0x14, 0x41,
	0x10, 0xdd, 0x89, 0x71, 0xd7, 0x74, 0x22, 0xe2, 0x10, 0x74, 0x76, 0xc1, 0x89, 0x89, 0x17, 0x09,
	0xec, 0xb4, 0xc1, 0x9b, 0xe0, 0x21, 0x8b, 0x0a, 0x1e, 0x24, 0x30, 0xc1, 0x8b, 0x97, 0x61, 0xbe,
	0xe8, 0x34, 0x6e, 0x77, 0x75, 0xa6, 0x6a, 0x92, 0xf5, 0xea, 0xd1, 0x93, 0x3f, 0x25, 0x87, 0xfc,
	0x88, 0x80, 0x97, 0x90, 0x93, 0x78, 0x08, 0xb2, 0x7b, 0xc8, 0xdf, 0x90, 0xfe, 0xf8, 0x05, 0x5e,
	0x86, 0xae, 0xf7, 0xa6, 0x5e, 0xd5, 0x7b, 0xdd, 0x6c, 0x7c, 0x5a, 0x51, 0xcd, 0xe7, 0x86, 0x9f,
	0x1d, 0x70, 0x85, 0xa2, 0xc0, 0xf3, 0xd2, 0x64, 0xa6, 0x03, 0x82, 0x98, 0x59, 0x2a, 0x9b, 0x9b,
	0xec, 0xec, 0x60, 0xf2, 0xb8, 0x54, 0x52, 0x03, 0x77, 0x5f, 0x4f, 0x4f, 0x9e, 0xd6, 0x80, 0x0a,
	0xd0, 0x76, 0x85, 0xe6, 0x40, 0x8c, 0x3d, 0x51, 0xb8, 0x8a, 0xfb, 0x22, 0x50, 0xdb, 0x02, 0x04,
	0x78, 0xdc, 0x9e, 0x3c, 0xba, 0xf7, 0x6b, 0x8d, 0x8d, 0x3e, 0xa1, 0x38, 0x3e, 0x2f, 0x4d, 0xfc,
	0x8a, 0x0d, 0x51, 0x0a, 0xdd, 0x76, 0x49, 0xf4, 0x3c, 0x7a, 0xb9, 0x31, 0x4b, 0x6e, 0x2e, 0xa7,
	0xdb, 0x41, 0xe3, 0xb0, 0x69, 0xba, 0x16, 0xf1, 0x98, 0x3a, 0xa9, 0x45, 0x1e, 0xfe, 0x8b, 0x77,
	0xd9, 0x16, 0x42, 0xdf, 0xd5, 0x6d, 0xd1, 0xb4, 0x1a, 0x54, 0xb2, 0x66, 0xfb, 0xf2, 0x4d, 0x8f,
	0xbd, 0xb3, 0x50, 0xfc, 0x9e, 0x0d, 0x4b, 0x05, 0xbd, 0xa6, 0xe4, 0x9e, 0x13, 0x9d, 0x5e, 0xdd,
	0xee, 0x0c, 0xfe, 0xdc, 0xee, 0x3c, 0xf1, 0xc2, 0xd8, 0x7c, 0xcd, 0x24, 0x70, 0x55, 0xd2, 0x49,
	0xf6, 0x59, 0x6a, 0xba, 0xb9, 0x9c, 0x6e, 0x86, 0x91, 0xb6, 0xcc, 0x43, 0x73, 0xfc, 0x81, 0x8d,
	0x94, 0xd4, 0x05, 0xf4, 0x94, 0xac, 0xff, 0x97, 0x8e, 0x92, 0xfa, 0xa8, 0xa7, 0xf8, 0x19, 0x63,
	0x4d, 0x8b, 0x14, 0xf6, 0xbd, 0xef, 0xf6, 0xdd, 0xb0, 0x88, 0xdf, 0x76, 0x97, 0x6d, 0x39, 0xba,
	0xf4, 0x76, 0x93, 0xa1, 0x37, 0x64, 0xb1, 0x90, 0xc0, 0x9b, 0xc9, 0xf7, 0xbb, 0x8b, 0xfd, 0x10,
	0xc0, 0x8f, 0xbb, 0x8b, 0x7d, 0x36, 0x37, 0x3c, 0x24, 0xb8, 0x27, 0xd8, 0xa3, 0x70, 0xcc, 0x5b,
	0x34, 0xa0, 0xb1, 0xb5, 0x03, 0xa1, 0xa7, 0x22, 0x64, 0x10, 0xf9, 0x81, 0xd0, 0xd3, 0xa1, 0xf7,
	0x35, 0x66, 0x0f, 0x70, 0x2e, 0x4d, 0x51, 0x19, 0x74, 0xe9, 0x3d, 0xcc, 0x47, 0xb6, 0x9e, 0x19,
	0x8c, 0x27, 0x6c, 0x83, 0x16, 0xd6, 0x71, 0x21, 0x1b, 0x17, 0xde, 0x7a, 0x3e, 0xa2, 0xc5, 0x51,
	0x4f, 0x1f, 0x9b, 0xd9, 0xdb, 0xab, 0x65, 0x1a, 0x5d, 0x2f, 0xd3, 0xe8, 0xef, 0x32, 0x8d, 0x7e,
	0xae, 0xd2, 0xc1, 0xf5, 0x2a, 0x1d, 0xfc, 0x5e, 0xa5, 0x83, 0x2f, 0x2f, 0x84, 0xa4, 0x93, 0xbe,
	0xca, 0x6a, 0x50, 0xbc, 0xa2, 0xfa, 0x74, 0x0a, 0x9d, 0xe0, 0xee, 0xa1, 0x2d, 0xec, 0x53, 0xa3,
	0x6f, 0xa6, 0xc5, 0x6a, 0xe8, 0x2e, 0xff, 0xf5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x45,
	0x94, 0x6d, 0x82, 0x02, 0x00, 0x00,
}

func (m *MsgSwap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DestAddress) > 0 {
		i -= len(m.DestAddress)
		copy(dAtA[i:], m.DestAddress)
		i = encodeVarintMsgSwap(dAtA, i, uint64(len(m.DestAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DestDenom) > 0 {
		i -= len(m.DestDenom)
		copy(dAtA[i:], m.DestDenom)
		i = encodeVarintMsgSwap(dAtA, i, uint64(len(m.DestDenom)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.MinOut.Size()
		i -= size
		if _, err := m.MinOut.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.SourceDenom) > 0 {
		i -= len(m.SourceDenom)
		copy(dAtA[i:], m.SourceDenom)
		i = encodeVarintMsgSwap(dAtA, i, uint64(len(m.SourceDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgSwap(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSwapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxOutId != 0 {
		i = encodeVarintMsgSwap(dAtA, i, uint64(m.TxOutId))
		i--
		dAtA[i] = 0x18
	}
	if m.SlipBps != 0 {
		i = encodeVarintMsgSwap(dAtA, i, uint64(m.SlipBps))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OutAmount) > 0 {
		i -= len(m.OutAmount)
		copy(dAtA[i:], m.OutAmount)
		i = encodeVarintMsgSwap(dAtA, i, uint64(len(m.OutAmount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgSwap(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgSwap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSwap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgSwap(uint64(l))
	}
	l = len(m.SourceDenom)
	if l > 0 {
		n += 1 + l + sovMsgSwap(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovMsgSwap(uint64(l))
	l = m.MinOut.Size()
	n += 1 + l + sovMsgSwap(uint64(l))
	l = len(m.DestDenom)
	if l > 0 {
		n += 1 + l + sovMsgSwap(uint64(l))
	}
	l = len(m.DestAddress)
	if l > 0 {
		n += 1 + l + sovMsgSwap(uint64(l))
	}
	return n
}

func (m *MsgSwapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OutAmount)
	if l > 0 {
		n += 1 + l + sovMsgSwap(uint64(l))
	}
	if m.SlipBps != 0 {
		n += 1 + sovMsgSwap(uint64(m.SlipBps))
	}
	if m.TxOutId != 0 {
		n += 1 + sovMsgSwap(uint64(m.TxOutId))
	}
	return n
}

func sovMsgSwap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgSwap(x uint64) (n int) {
	return sovMsgSwap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSwap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSwapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlipBps", wireType)
			}
			m.SlipBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlipBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOutId", wireType)
			}
			m.TxOutId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxOutId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgSwap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgSwap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgSwap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgSwap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgSwap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgSwap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgSwap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgSwap = fmt.Errorf("proto: unexpected end of group")
)
