name: Release

on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: go.sum
      - name: Build
        run: make build
      - name: Rename binary
        shell: bash
        run: |
          mv build/qbtcd build/qbtcd-${{ matrix.goos }}-${{ matrix.goarch }}
          mv build/bifrost build/bifrost-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/qbtcd-${{ matrix.goos }}-${{ matrix.goarch }}
            build/bifrost-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}