// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbtc/ebifrost/v1/server.proto

package ebifrost

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SubscribeRequest is a request to subscribe to events emitted by btcq node.
type SubscribeRequest struct {
	// Optional fields to filter what events to subscribe to
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91c55c4f8296e5b, []int{0}
}
func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetEventTypes() []string {
	if m != nil {
		return m.EventTypes
	}
	return nil
}

// EventNotification is a notification of an event emitted by btcq node.
type EventNotification struct {
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *EventNotification) Reset()         { *m = EventNotification{} }
func (m *EventNotification) String() string { return proto.CompactTextString(m) }
func (*EventNotification) ProtoMessage()    {}
func (*EventNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91c55c4f8296e5b, []int{1}
}
func (m *EventNotification) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventNotification.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNotification.Merge(m, src)
}
func (m *EventNotification) XXX_Size() int {
	return m.Size()
}
func (m *EventNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNotification.DiscardUnknown(m)
}

var xxx_messageInfo_EventNotification proto.InternalMessageInfo

func (m *EventNotification) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventNotification) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EventNotification) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "qbtc.ebifrost.v1.SubscribeRequest")
	proto.RegisterType((*EventNotification)(nil), "qbtc.ebifrost.v1.EventNotification")
}

func init() { proto.RegisterFile("qbtc/ebifrost/v1/server.proto", fileDescriptor_b91c55c4f8296e5b) }

var fileDescriptor_b91c55c4f8296e5b = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xbf, 0xd2, 0x8f, 0x62, 0x18, 0x5a, 0x4f, 0x11, 0xa2, 0x26, 0x0a, 0x4b, 0x16,
	0x6c, 0x4a, 0xdf, 0x20, 0x12, 0x1b, 0x62, 0x08, 0x9d, 0x18, 0x40, 0xb1, 0x71, 0x5b, 0xa3, 0xa6,
	0x4e, 0xec, 0x9b, 0x88, 0xbe, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0x2f, 0x82, 0x12, 0xd4,
	0x56, 0xb4, 0xe3, 0x3d, 0xe7, 0x1e, 0xe9, 0x9c, 0x0f, 0x8f, 0x0a, 0x01, 0x92, 0x2b, 0xa1, 0x67,
	0xd6, 0x38, 0xe0, 0xd5, 0x98, 0x3b, 0x65, 0x2b, 0x65, 0x59, 0x6e, 0x0d, 0x18, 0x32, 0x68, 0x6d,
	0xb6, 0xb5, 0x59, 0x35, 0x0e, 0x27, 0x78, 0xf0, 0x58, 0x0a, 0x27, 0xad, 0x16, 0x2a, 0x51, 0x45,
	0xa9, 0x1c, 0x90, 0x4b, 0x7c, 0xaa, 0x2a, 0xb5, 0x82, 0x17, 0x58, 0xe7, 0xca, 0xf9, 0x28, 0xe8,
	0x47, 0x5e, 0x82, 0x3b, 0x69, 0xda, 0x2a, 0xe1, 0x1b, 0x1e, 0xde, 0xb5, 0xd7, 0x83, 0x01, 0x3d,
	0xd3, 0x32, 0x05, 0x6d, 0x56, 0x64, 0x84, 0xf1, 0x3e, 0xe5, 0xa3, 0x00, 0x45, 0x5e, 0xe2, 0xed,
	0x42, 0xc4, 0xc7, 0x27, 0x79, 0xba, 0x5e, 0x9a, 0xf4, 0xd5, 0xff, 0x17, 0xa0, 0xe8, 0x2c, 0xd9,
	0x9e, 0xe4, 0x02, 0x7b, 0xa0, 0x33, 0xe5, 0x20, 0xcd, 0x72, 0xbf, 0x1f, 0xa0, 0xa8, 0x9f, 0xec,
	0x85, 0x5b, 0x8b, 0x07, 0xf7, 0x46, 0xa6, 0xcb, 0x85, 0x71, 0x10, 0xff, 0xf6, 0x26, 0xcf, 0x78,
	0xb8, 0x2b, 0x3d, 0x35, 0x5d, 0x15, 0x47, 0x42, 0x76, 0x38, 0x8e, 0x1d, 0x2e, 0x3b, 0xbf, 0x3a,
	0xfe, 0x39, 0x1a, 0x72, 0x83, 0xe2, 0xf8, 0xb3, 0xa6, 0x68, 0x53, 0x53, 0xf4, 0x5d, 0x53, 0xf4,
	0xd1, 0xd0, 0xde, 0xa6, 0xa1, 0xbd, 0xaf, 0x86, 0xf6, 0x9e, 0xa2, 0xb9, 0x86, 0x45, 0x29, 0x98,
	0x34, 0x19, 0x17, 0x20, 0x8b, 0x6b, 0x63, 0xe7, 0xbc, 0x63, 0xfe, 0xce, 0xff, 0xa0, 0x17, 0xff,
	0x3b, 0xe2, 0x93, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0xac, 0x40, 0xef, 0x92, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocalhostBifrostClient is the client API for LocalhostBifrost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocalhostBifrostClient interface {
	// SubscribeToEvents streams event notifications that match the requested
	// types.
	SubscribeToEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (LocalhostBifrost_SubscribeToEventsClient, error)
}

type localhostBifrostClient struct {
	cc grpc1.ClientConn
}

func NewLocalhostBifrostClient(cc grpc1.ClientConn) LocalhostBifrostClient {
	return &localhostBifrostClient{cc}
}

func (c *localhostBifrostClient) SubscribeToEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (LocalhostBifrost_SubscribeToEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LocalhostBifrost_serviceDesc.Streams[0], "/qbtc.ebifrost.v1.LocalhostBifrost/SubscribeToEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &localhostBifrostSubscribeToEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LocalhostBifrost_SubscribeToEventsClient interface {
	Recv() (*EventNotification, error)
	grpc.ClientStream
}

type localhostBifrostSubscribeToEventsClient struct {
	grpc.ClientStream
}

func (x *localhostBifrostSubscribeToEventsClient) Recv() (*EventNotification, error) {
	m := new(EventNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LocalhostBifrostServer is the server API for LocalhostBifrost service.
type LocalhostBifrostServer interface {
	// SubscribeToEvents streams event notifications that match the requested
	// types.
	SubscribeToEvents(*SubscribeRequest, LocalhostBifrost_SubscribeToEventsServer) error
}

// UnimplementedLocalhostBifrostServer can be embedded to have forward compatible implementations.
type UnimplementedLocalhostBifrostServer struct {
}

func (*UnimplementedLocalhostBifrostServer) SubscribeToEvents(req *SubscribeRequest, srv LocalhostBifrost_SubscribeToEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToEvents not implemented")
}

func RegisterLocalhostBifrostServer(s grpc1.Server, srv LocalhostBifrostServer) {
	s.RegisterService(&_LocalhostBifrost_serviceDesc, srv)
}

func _LocalhostBifrost_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalhostBifrostServer).SubscribeToEvents(m, &localhostBifrostSubscribeToEventsServer{stream})
}

type LocalhostBifrost_SubscribeToEventsServer interface {
	Send(*EventNotification) error
	grpc.ServerStream
}

type localhostBifrostSubscribeToEventsServer struct {
	grpc.ServerStream
}

func (x *localhostBifrostSubscribeToEventsServer) Send(m *EventNotification) error {
	return x.ServerStream.SendMsg(m)
}

var LocalhostBifrost_serviceDesc = _LocalhostBifrost_serviceDesc
var _LocalhostBifrost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qbtc.ebifrost.v1.LocalhostBifrost",
	HandlerType: (*LocalhostBifrostServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _LocalhostBifrost_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "qbtc/ebifrost/v1/server.proto",
}

func (m *SubscribeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubscribeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubscribeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EventTypes) > 0 {
		for iNdEx := len(m.EventTypes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EventTypes[iNdEx])
			copy(dAtA[i:], m.EventTypes[iNdEx])
			i = encodeVarintServer(dAtA, i, uint64(len(m.EventTypes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EventNotification) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventNotification) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventNotification) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintServer(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintServer(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EventType) > 0 {
		i -= len(m.EventType)
		copy(dAtA[i:], m.EventType)
		i = encodeVarintServer(dAtA, i, uint64(len(m.EventType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintServer(dAtA []byte, offset int, v uint64) int {
	offset -= sovServer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubscribeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EventTypes) > 0 {
		for _, s := range m.EventTypes {
			l = len(s)
			n += 1 + l + sovServer(uint64(l))
		}
	}
	return n
}

func (m *EventNotification) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EventType)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovServer(uint64(m.Timestamp))
	}
	return n
}

func sovServer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServer(x uint64) (n int) {
	return sovServer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubscribeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubscribeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubscribeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventTypes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventTypes = append(m.EventTypes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventNotification) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventNotification: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventNotification: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServer = fmt.Errorf("proto: unexpected end of group")
)
